export const getCourses = [
  {
    id: 1,
    title: "AIRCRAFT MAINTENANCE",
    moCode: "21MO0004",
    mgCode: null,
    duration: "4",
  },
  {
    id: 2,
    title: "AN INTERFACE WITH BIOLOGY AND MEDICINE",
    moCode: "21MO0006",
    mgCode: null,
    duration: "8",
  },
  {
    id: 3,
    title: "APPLIED NATURAL PROCESSING",
    moCode: "21MO0015",
    mgCode: null,
    duration: "12",
  },
  {
    id: 4,
    title: "BIOREACTOR DESIGN AND ANALYSIS",
    moCode: "21MO0042",
    mgCode: "24MG0057",
    duration: "8",
  },
  {
    id: 5,
    title: "BRIEF INTRODUCTION TO PSYCHOLOGY",
    moCode: "21MO0048",
    mgCode: null,
    duration: "4",
  },
  {
    id: 6,
    title: "CELL CULTURE TECHNOLOGIES",
    moCode: "21MO0057",
    mgCode: "24MG0119",
    duration: "8",
  },
  {
    id: 7,
    title: "CLASSICAL SOCIOLOGICAL THEORY",
    moCode: "21MO0060",
    mgCode: null,
    duration: "12",
  },
  {
    id: 8,
    title: "CLOUD COMPUTING AND DISTRIBUTED SYSTEMS",
    moCode: "21MO0061",
    mgCode: "23MG0030",
    duration: "8",
  },
  {
    id: 9,
    title: "COMMUNICATION SKILLS",
    moCode: "21MO0064",
    mgCode: null,
    duration: "12",
  },
  {
    id: 10,
    title: "COMPUTER APPLICATION IN BUSINESS",
    moCode: "21MO0066",
    mgCode: null,
    duration: "12",
  },
  {
    id: 11,
    title:
      "CONSTITUTION OF INDIA AND ENVIRONMENTAL GOVERNANCE: ADMINISTRATIVE AND ADJUDICATORY PROCESS",
    moCode: "21MO0069",
    mgCode: null,
    duration: "12",
  },
  {
    id: 12,
    title:
      "CURRENT REGULATORY REQUIREMENTS FOR CONDUCTING CLINICAL TRIALS IN INDIA FOR INVESTIGATIONAL NEW DRUGS/NEW DRUG (VERSION 3.0)",
    moCode: "21MO0078",
    mgCode: "24MG0121",
    duration: "8",
  },
  {
    id: 13,
    title: "DEMYSTIFYING THE BRAIN",
    moCode: "21MO0097",
    mgCode: null,
    duration: "4",
  },
  {
    id: 14,
    title: "DESCRIPTIVE STATISTICS WITH R SOFTWARE",
    moCode: "21MO0098",
    mgCode: null,
    duration: "8",
  },
  {
    id: 15,
    title: "DESIGN THINKING - A PRIMER",
    moCode: "21MO0101",
    mgCode: null,
    duration: "4",
  },
  {
    id: 16,
    title: "DEVELOPING SOFT SKILLS AND PERSONALITY",
    moCode: "21MO0106",
    mgCode: "23MG0013",
    duration: "8",
  },
  {
    id: 17,
    title: "DEVELOPMENT RESEARCH METHODS",
    moCode: "21MO0108",
    mgCode: null,
    duration: "8",
  },
  {
    id: 18,
    title: "EARTH SCIENCES FOR CIVIL ENGINEERING PART - I & II",
    moCode: "21MO0115",
    mgCode: null,
    duration: "8",
  },
  {
    id: 19,
    title: "EMOTIONAL INTELLIGENCE",
    moCode: "21MO0121",
    mgCode: "24MG0001",
    duration: "12",
  },
  {
    id: 20,
    title: "ENGLISH LANGUAGE FOR COMPETITIVE EXAMS",
    moCode: "21MO0123",
    mgCode: "23MG0078",
    duration: "12",
  },
  {
    id: 21,
    title: "FINANCIAL INSTITUTIONS AND MARKETS",
    moCode: "21MO0134",
    mgCode: null,
    duration: "12",
  },
  {
    id: 22,
    title: "FOOD NUTRITION FOR HEALTHY LIVING",
    moCode: "21MO0139",
    mgCode: null,
    duration: "24",
  },
  {
    id: 23,
    title: "FORESTS AND THEIR MANAGEMENT",
    moCode: "21MO0140",
    mgCode: "24MG0046",
    duration: "12",
  },
  {
    id: 24,
    title: "FOUNDATION COURSE IN MANAGERIAL ECONOMICS",
    moCode: "21MO0141",
    mgCode: null,
    duration: "8",
  },
  {
    id: 25,
    title: "FUZZY SETS, LOGIC AND SYSTEMS & APPLICATIONS",
    moCode: "21MO0151",
    mgCode: null,
    duration: "12",
  },
  {
    id: 26,
    title: "GENDER JUSTICE AND WORKPLACE SECURITY",
    moCode: "21MO0152",
    mgCode: null,
    duration: "4",
  },
  {
    id: 27,
    title: "GERMAN-I",
    moCode: "21MO0156",
    mgCode: "24MG0002",
    duration: "12",
  },
  {
    id: 28,
    title: "GREAT EXPERIMENTS IN PSYCHOLOGY",
    moCode: "21MO0167",
    mgCode: "24MG0003",
    duration: "4",
  },
  {
    id: 29,
    title: "HUMAN BEHAVIOUR",
    moCode: "21MO0175",
    mgCode: "23MG0085",
    duration: "8",
  },
  {
    id: 30,
    title: "HUMAN MOLECULAR GENETICS",
    moCode: "21MO0176",
    mgCode: null,
    duration: "4",
  },
  {
    id: 31,
    title: "HUMAN RESOURCE DEVELOPMENT",
    moCode: "21MO0178",
    mgCode: null,
    duration: "12",
  },
  {
    id: 32,
    title: "HUMAN RIGHTS LAW AND CRIMINAL JUSTICE",
    moCode: "21MO0179",
    mgCode: null,
    duration: "12",
  },
  {
    id: 33,
    title: "INTRODUCTION TO DEVELOPMENT BIOLOGY",
    moCode: "21MO0218",
    mgCode: null,
    duration: "12",
  },
  {
    id: 34,
    title: "INTRODUCTION TO EXPERIMENTS IN FLIGHT",
    moCode: "21MO0220",
    mgCode: "24MG0004",
    duration: "4",
  },
  {
    id: 35,
    title: "INTRODUCTION TO INDUSTRY 4.0 AND INDUSTRIAL INTERNET OF THINGS",
    moCode: "21MO0227",
    mgCode: "23MG0031",
    duration: "12",
  },
  {
    id: 36,
    title: "INTRODUCTION TO INTERNET OF THINGS",
    moCode: "21MO0229",
    mgCode: "23MG0007",
    duration: "12",
  },
  {
    id: 37,
    title: "INTRODUCTION TO LAW ON ELECTRICITY",
    moCode: "21MO0232",
    mgCode: null,
    duration: "8",
  },
  {
    id: 38,
    title: "INTRODUCTION TO R SOFTWARE",
    moCode: "21MO0239",
    mgCode: null,
    duration: "8",
  },
  {
    id: 39,
    title: "INTRODUCTION TO RESEARCH",
    moCode: "21MO0240",
    mgCode: null,
    duration: "8",
  },
  {
    id: 40,
    title: "INTRODUCTORY MATHEMATICAL METHODS FOR BIOLOGISTS",
    moCode: "21MO0249",
    mgCode: "24MG0111",
    duration: "8",
  },
  {
    id: 41,
    title: "LEGAL AND REGULATORY ISSUES IN BIOTECHNOLOGY",
    moCode: "21MO0257",
    mgCode: null,
    duration: "4",
  },
  {
    id: 42,
    title: "MACHINING SCIENCE",
    moCode: "21MO0265",
    mgCode: null,
    duration: "4",
  },
  {
    id: 43,
    title: "ORGANIZATION THEORY / STRUCTURE AND DESIGN",
    moCode: "21MO0283",
    mgCode: null,
    duration: "12",
  },
  {
    id: 44,
    title: "ORGANIZATIONAL BEHAVIOUR I",
    moCode: "21MO0284",
    mgCode: null,
    duration: "12",
  },
  {
    id: 45,
    title: "ORGANIZATIONAL BEHAVIOUR II",
    moCode: "21MO0285",
    mgCode: null,
    duration: "12",
  },
  {
    id: 46,
    title: "PATENT LAW FOR ENGINEERS AND SCIENTISTS",
    moCode: "21MO0288",
    mgCode: null,
    duration: "12",
  },
  {
    id: 47,
    title: "PRINCIPLES OF GENETICS",
    moCode: "21MO0297",
    mgCode: null,
    duration: "12",
  },
  {
    id: 48,
    title: "PRINCIPLES OF HUMAN RESOURCE MANAGEMENT",
    moCode: "21MO0298",
    mgCode: null,
    duration: "8",
  },
  {
    id: 49,
    title: "PROBABILITY AND STATISTICS",
    moCode: "21MO0301",
    mgCode: null,
    duration: "12",
  },
  {
    id: 50,
    title: "PROJECT ANALYSIS",
    moCode: "21MO0308",
    mgCode: null,
    duration: "12",
  },
  {
    id: 51,
    title: "PROPERTIES OF MATERIAL(NATURE AND PROPERTIES OF MATERIAL:III)",
    moCode: "21MO0310",
    mgCode: null,
    duration: "8",
  },
  {
    id: 52,
    title: "PYTHON FOR DATA SCIENCE",
    moCode: "21MO0315",
    mgCode: "23MG0032",
    duration: "4",
  },
  {
    id: 53,
    title: "REGRESSION ANALYSIS",
    moCode: "21MO0320",
    mgCode: null,
    duration: "12",
  },
  {
    id: 54,
    title: "REINFORCEMENT LEARNING",
    moCode: "21MO0321",
    mgCode: "24MG0005",
    duration: "12",
  },
  {
    id: 55,
    title: "RIGHT TO INFORMATION AND GOOD GOVERNANCE",
    moCode: "21MO0324",
    mgCode: null,
    duration: "12",
  },
  {
    id: 56,
    title: "SCHEDULING TECHINQUES IN PROJECTS",
    moCode: "21MO0326",
    mgCode: null,
    duration: "4",
  },
  {
    id: 57,
    title: "SENSORS AND ACTUATORS",
    moCode: "21MO0328",
    mgCode: null,
    duration: "12",
  },
  {
    id: 58,
    title: "SMART MATERIALS AND INTELLIGENT SYSTEM DESIGN",
    moCode: "21MO0335",
    mgCode: null,
    duration: "4",
  },
  {
    id: 59,
    title: "SOCIAL NETWORKS",
    moCode: "21MO0336",
    mgCode: "23MG0033",
    duration: "12",
  },
  {
    id: 60,
    title: "SOCIOLOGY OF DEVELOPMENT",
    moCode: "21MO0339",
    mgCode: null,
    duration: "12",
  },
  {
    id: 61,
    title: "SOFT NANOTECHNOLOGY",
    moCode: "21MO0340",
    mgCode: null,
    duration: "8",
  },
  {
    id: 62,
    title: "SOFTWARE TESTING",
    moCode: "21MO0341",
    mgCode: "23MG0034",
    duration: "12",
  },
  {
    id: 63,
    title: "STRESS MANAGEMENT",
    moCode: "21MO0347",
    mgCode: null,
    duration: "4",
  },
  {
    id: 64,
    title: "STRUCTURAL BIOLOGY",
    moCode: "21MO0349",
    mgCode: "24MG0058",
    duration: "12",
  },
  {
    id: 65,
    title: "DATA MINING",
    moCode: "21MO0412",
    mgCode: "23MG0035",
    duration: "8",
  },
  {
    id: 66,
    title: "ADVANCED MACHINING PROCESSES",
    moCode: "21MO0414",
    mgCode: null,
    duration: "8",
  },
  {
    id: 67,
    title: "HUMAN RIGHTS, LAW AND CRIMINAL JUSTICE",
    moCode: "21MO0417",
    mgCode: null,
    duration: "12",
  },
  {
    id: 68,
    title: "ADVANCED GRAPH THEORY",
    moCode: "21MO0431",
    mgCode: null,
    duration: "8",
  },
  {
    id: 69,
    title: "AIRCRAFT DESIGN",
    moCode: "21MO0432",
    mgCode: null,
    duration: "12",
  },
  {
    id: 70,
    title: "AIRCRAFT PROPULSION",
    moCode: "21MO0433",
    mgCode: null,
    duration: "12",
  },
  {
    id: 71,
    title: "AN INTRODUCTION TO ARTIFICIAL INTELLIGENCE",
    moCode: "21MO0435",
    mgCode: null,
    duration: "12",
  },
  {
    id: 72,
    title: "BIG DATA COMPUTING",
    moCode: "21MO0447",
    mgCode: "23MG0036",
    duration: "8",
  },
  {
    id: 73,
    title: "BIOLOGICAL INORGANIC CHEMISTRY",
    moCode: "21MO0448",
    mgCode: null,
    duration: "12",
  },
  {
    id: 74,
    title: "BLOCKCHAIN AND ITS APPLICATIONS",
    moCode: "21MO0450",
    mgCode: "24MG0006",
    duration: "12",
  },
  {
    id: 75,
    title: "CLOUD COMPUTING",
    moCode: "21MO0459",
    mgCode: null,
    duration: "8",
  },
  {
    id: 76,
    title: "COGNITION, TRANSFORMATION, AND LIVES",
    moCode: "21MO0460",
    mgCode: null,
    duration: "4",
  },
  {
    id: 77,
    title: "DAIRY AND FOOD PROCESS AND PRODUCTS TECHNOLOGY",
    moCode: "21MO0466",
    mgCode: "23MG0073",
    duration: "12",
  },
  {
    id: 78,
    title: "DATA ANALYTICS WITH PYTHON",
    moCode: "21MO0467",
    mgCode: "24MG0007",
    duration: "12",
  },
  {
    id: 79,
    title: "DEEP LEARNING",
    moCode: "21MO0471",
    mgCode: "24MG0090",
    duration: "12",
  },
  {
    id: 80,
    title: "DIGITAL CIRCUITS",
    moCode: "21MO0473",
    mgCode: "23MG0002",
    duration: "12",
  },
  {
    id: 81,
    title: "ELEMENTS OF LITERATURE AND CREATIVE COMMUNICATION",
    moCode: "21MO0476",
    mgCode: null,
    duration: "12",
  },
  {
    id: 82,
    title: "EMBEDDED SYSTEMS DESIGN",
    moCode: "21MO0477",
    mgCode: null,
    duration: "12",
  },
  {
    id: 83,
    title: "ENGLISH LITERATURE OF THE ROMANTIC PERIOD, 1798-1832",
    moCode: "21MO0482",
    mgCode: null,
    duration: "8",
  },
  {
    id: 84,
    title: "ENVIRONMENTAL IMPACT ASSESSMENT",
    moCode: "21MO0483",
    mgCode: null,
    duration: "12",
  },
  {
    id: 85,
    title: "ENVIRONMENTAL REMEDIATION AND CONTAMINATED SITES",
    moCode: "21MO0484",
    mgCode: null,
    duration: "12",
  },
  {
    id: 86,
    title: "ETHICAL HACKING",
    moCode: "21MO0486",
    mgCode: "24MG0072",
    duration: "12",
  },
  {
    id: 87,
    title: "FOOD AND NUTRITION",
    moCode: "21MO0487",
    mgCode: null,
    duration: "12",
  },
  {
    id: 88,
    title: "FOOD LAWS AND STANDARDS",
    moCode: "21MO0488",
    mgCode: null,
    duration: "16",
  },
  {
    id: 89,
    title: "FOOD MICROBIOLOGY AND FOOD SAFETY",
    moCode: "21MO0489",
    mgCode: null,
    duration: "15",
  },
  {
    id: 90,
    title: "FUNCTIONAL FOODS AND NEUTRACEUTICALS",
    moCode: "21MO0491",
    mgCode: null,
    duration: "15",
  },
  {
    id: 91,
    title: "FUNDAMENTALS OF ARTIFICIAL INTELLIGENCE",
    moCode: "21MO0492",
    mgCode: "24MG0081",
    duration: "12",
  },
  {
    id: 92,
    title: "FUNDAMENTALS OF AUTOMOTIVE SYSTEMS",
    moCode: "21MO0493",
    mgCode: null,
    duration: "12",
  },
  {
    id: 93,
    title: "FUNDAMENTALS OF COMPUTER SYSTEM",
    moCode: "21MO0494",
    mgCode: null,
    duration: "12",
  },
  {
    id: 94,
    title: "GERMAN-II",
    moCode: "21MO0501",
    mgCode: "24MG0008",
    duration: "12",
  },
  {
    id: 95,
    title: "GETTING STARTED WITH COMPETITIVE PROGRAMMING",
    moCode: "21MO0502",
    mgCode: "24MG0009",
    duration: "12",
  },
  {
    id: 96,
    title: "GPU ARCHITECTURES AND PROGRAMMING",
    moCode: "21MO0505",
    mgCode: "24MG0010",
    duration: "12",
  },
  {
    id: 97,
    title: "HISTORY OF ENGLISH LANGUAGE AND LITERATURE",
    moCode: "21MO0506",
    mgCode: "24MG0074",
    duration: "12",
  },
  {
    id: 98,
    title: "INFORMATION SECURITY - 5 - SECURE SYSTEMS ENGINEERING",
    moCode: "21MO0509",
    mgCode: "23MG0037",
    duration: "8",
  },
  {
    id: 99,
    title: "INSTRUMENTATION AND PROCESS CONTROL IN FOOD INDUSTRY",
    moCode: "21MO0510",
    mgCode: null,
    duration: "8",
  },
  {
    id: 100,
    title: "INTRODUCTION TO ALGORITHMS AND ANALYSIS",
    moCode: "21MO0511",
    mgCode: null,
    duration: "12",
  },
  {
    id: 101,
    title: "INTRODUCTION TO BASIC COGNITIVE PROCESSES",
    moCode: "21MO0513",
    mgCode: "23MG0014",
    duration: "8",
  },
  {
    id: 102,
    title: "INTRODUCTION TO JAPANESE LANGUAGE AND CULTURE",
    moCode: "21MO0518",
    mgCode: null,
    duration: "12",
  },
  {
    id: 103,
    title: "INTRODUCTION TO LAUNCH VEHICLE ANALYSIS AND DESIGN",
    moCode: "21MO0519",
    mgCode: null,
    duration: "8",
  },
  {
    id: 104,
    title: "INTRODUCTION TO PSYCHOLOGY",
    moCode: "21MO0525",
    mgCode: "23MG0015",
    duration: "8",
  },
  {
    id: 105,
    title: "INTRODUCTION TO SEMICONDUCTOR DEVICES",
    moCode: "21MO0526",
    mgCode: "24MG0106",
    duration: "12",
  },
  {
    id: 106,
    title: "INTRODUCTION TO WORLD LITERATURE",
    moCode: "21MO0529",
    mgCode: null,
    duration: "12",
  },
  {
    id: 107,
    title: "MEDICAL BIOMATERIALS",
    moCode: "21MO0534",
    mgCode: "24MG0059",
    duration: "8",
  },
  {
    id: 108,
    title: "MULTI-CORE COMPUTER ARCHITECTURE - STORAGE AND INTERCONNECTS",
    moCode: "21MO0535",
    mgCode: null,
    duration: "8",
  },
  {
    id: 109,
    title: "NANOTECHNOLOGY IN AGRICULTURE",
    moCode: "21MO0536",
    mgCode: "23MG0011",
    duration: "8",
  },
  {
    id: 110,
    title: "NUCLEAR ASTROPHYSICS",
    moCode: "21MO0539",
    mgCode: null,
    duration: "8",
  },
  {
    id: 111,
    title: "ONLINE PRIVACY",
    moCode: "21MO0540",
    mgCode: null,
    duration: "12",
  },
  {
    id: 112,
    title: "PROGRAMMING IN MODERN C++",
    moCode: "21MO0547",
    mgCode: "23MG0038",
    duration: "12",
  },
  {
    id: 113,
    title: "PROGRAMMING, DATA STRUCTURES AND ALGORITHMS USING PYTHON",
    moCode: "21MO0549",
    mgCode: "24MG0107",
    duration: "8",
  },
  {
    id: 114,
    title: "RURAL WATER RESOURCES MANAGEMENT",
    moCode: "21MO0553",
    mgCode: null,
    duration: "12",
  },
  {
    id: 115,
    title: "SAFETY IN CONSTRUCTION",
    moCode: "21MO0554",
    mgCode: null,
    duration: "8",
  },
  {
    id: 116,
    title: "SEMICONDUCTOR DEVICES AND CIRCUITS",
    moCode: "21MO0556",
    mgCode: null,
    duration: "12",
  },
  {
    id: 117,
    title: "SOFTWARE TESTING",
    moCode: "21MO0559",
    mgCode: null,
    duration: "4",
  },
  {
    id: 118,
    title: "SPEAKING EFFECTIVELY",
    moCode: "21MO0561",
    mgCode: "23MG0039",
    duration: "8",
  },
  {
    id: 119,
    title:
      "SPECTROSCOPIC TECHNIQUES FOR PHARMACEUTICAL AND BIOPHARMACEUTICAL COMPANIES",
    moCode: "21MO0562",
    mgCode: null,
    duration: "12",
  },
  {
    id: 120,
    title: "TECHNICAL ENGLISH FOR ENGINEERS",
    moCode: "21MO0565",
    mgCode: "23MG0068",
    duration: "8",
  },
  {
    id: 121,
    title: "THE JOY OF COMPUTING USING PYTHON",
    moCode: "21MO0568",
    mgCode: "23MG0079",
    duration: "12",
  },
  {
    id: 122,
    title: "THERMAL PROCESSING OF FOODS",
    moCode: "21MO0570",
    mgCode: null,
    duration: "12",
  },
  {
    id: 123,
    title: "VLSI PHYSICAL DESIGN",
    moCode: "21MO0575",
    mgCode: null,
    duration: "12",
  },
  {
    id: 124,
    title: "WORK SYSTEM DESIGN",
    moCode: "21MO0577",
    mgCode: null,
    duration: "12",
  },
  {
    id: 125,
    title: "ADVANCED COMPUTER ARCHITECTURE",
    moCode: "22MO0002",
    mgCode: null,
    duration: "8",
  },
  {
    id: 126,
    title: "ANIMAL PHYSIOLOGY",
    moCode: "22MO0005",
    mgCode: "23MG0009",
    duration: "12",
  },
  {
    id: 127,
    title: "APPLIED ERGONOMICS",
    moCode: "22MO0006",
    mgCode: null,
    duration: "12",
  },
  {
    id: 128,
    title: "BIOMEDICAL NANOTECHNOLOGY",
    moCode: "22MO0007",
    mgCode: "24MG0011",
    duration: "4",
  },
  {
    id: 129,
    title: "BIOREACTORS",
    moCode: "22MO0008",
    mgCode: null,
    duration: "4",
  },
  {
    id: 130,
    title: "COMPUTATIONAL GEOMETRY",
    moCode: "22MO0011",
    mgCode: null,
    duration: "12",
  },
  {
    id: 131,
    title: "COMPUTER AIDED DRUG DESIGN",
    moCode: "22MO0012",
    mgCode: null,
    duration: "8",
  },
  {
    id: 132,
    title: "DESIGN AND ENGINEERING OF COMPUTER SYSTEMS",
    moCode: "22MO0013",
    mgCode: null,
    duration: "8",
  },
  {
    id: 133,
    title: "DESIGN PRACTICE",
    moCode: "22MO0014",
    mgCode: null,
    duration: "8",
  },
  {
    id: 134,
    title: "ENVIRONMENTAL BIOTECHNOLOGY",
    moCode: "22MO0015",
    mgCode: null,
    duration: "12",
  },
  {
    id: 135,
    title: "EXPLOSIONS AND SAFETY",
    moCode: "22MO0017",
    mgCode: null,
    duration: "12",
  },
  {
    id: 136,
    title: "FUNDAMENTAL OF WELDING SCIENCE AND TECHNOLOGY",
    moCode: "22MO0018",
    mgCode: null,
    duration: "8",
  },
  {
    id: 137,
    title: "HARDWARE SECURITY",
    moCode: "22MO0021",
    mgCode: null,
    duration: "12",
  },
  {
    id: 138,
    title: "INDUSTRIAL BIOTECHNOLOGY",
    moCode: "22MO0023",
    mgCode: null,
    duration: "12",
  },
  {
    id: 139,
    title: "INNOVATION, BUSINESS MODELS AND ENTREPRENEURSHIP",
    moCode: "22MO0024",
    mgCode: "23MG0008",
    duration: "8",
  },
  {
    id: 140,
    title: "INTRODUCTION TO ABRASIVE MACHINING AND FINISHING PROCESSES",
    moCode: "22MO0026",
    mgCode: null,
    duration: "8",
  },
  {
    id: 141,
    title: "INTRODUCTION TO BIOSTATISTICS",
    moCode: "22MO0027",
    mgCode: null,
    duration: "8",
  },
  {
    id: 142,
    title: "INTRODUCTION TO DEVELOPMENTAL BIOLOGY",
    moCode: "22MO0028",
    mgCode: null,
    duration: "12",
  },
  {
    id: 143,
    title: "INTRODUCTION TO MACHINING AND MACHINING FLUIDS",
    moCode: "22MO0030",
    mgCode: null,
    duration: "8",
  },
  {
    id: 144,
    title: "INTRODUCTION TO PARALLEL PROGRAMMING WITH OPENMP AND MPI",
    moCode: "22MO0031",
    mgCode: null,
    duration: "8",
  },
  {
    id: 145,
    title: "INTRODUCTION TO UNCERTAINTY ANALYSIS AND EXPERIMENTATION",
    moCode: "22MO0034",
    mgCode: null,
    duration: "8",
  },
  {
    id: 146,
    title: "MANUFACTURING AUTOMATION",
    moCode: "22MO0035",
    mgCode: "23MG0091",
    duration: "4",
  },
  {
    id: 147,
    title: "MECHANICAL MEASUREMENT SYSTEM",
    moCode: "22MO0036",
    mgCode: null,
    duration: "8",
  },
  {
    id: 148,
    title: "MECHANICS OF MACHINING",
    moCode: "22MO0037",
    mgCode: null,
    duration: "8",
  },
  {
    id: 149,
    title: "MODEL CHECKING",
    moCode: "22MO0039",
    mgCode: null,
    duration: "12",
  },
  {
    id: 150,
    title: "NATURE AND PROPERTIES OF MATERIALS",
    moCode: "22MO0040",
    mgCode: null,
    duration: "8",
  },
  {
    id: 151,
    title: "PLANT CELL BIOPROCESSING",
    moCode: "22MO0042",
    mgCode: "24MG0112",
    duration: "8",
  },
  {
    id: 152,
    title: "PROGRAMMING IN JAVA",
    moCode: "22MO0044",
    mgCode: null,
    duration: "12",
  },
  {
    id: 153,
    title: "ROBOTICS AND CONTROL : THEORY AND PRACTICE",
    moCode: "22MO0045",
    mgCode: null,
    duration: "8",
  },
  {
    id: 154,
    title: "SOFT SKILLS",
    moCode: "22MO0046",
    mgCode: "23MG0074",
    duration: "12",
  },
  {
    id: 155,
    title: "SOFT SKILLS FOR BUSINESS NEGOTIATIONS AND MARKETING STRATEGIES",
    moCode: "22MO0047",
    mgCode: null,
    duration: "12",
  },
  {
    id: 156,
    title: "SOFTWARE CONCEPTUAL DESIGN",
    moCode: "22MO0048",
    mgCode: "23MG0040",
    duration: "4",
  },
  {
    id: 157,
    title: "STEAM AND GAS POWER SYSTEMS",
    moCode: "22MO0049",
    mgCode: null,
    duration: "8",
  },
  {
    id: 158,
    title: "SYSTEMS AND USABLE SECURITY",
    moCode: "22MO0050",
    mgCode: "23MG0041",
    duration: "4",
  },
  {
    id: 159,
    title: "TISSUE ENGINEERING",
    moCode: "22MO0051",
    mgCode: null,
    duration: "8",
  },
  {
    id: 160,
    title: "POLLUTANTS AND WATER SUPPLY",
    moCode: "22MO0053",
    mgCode: null,
    duration: "16",
  },
  {
    id: 161,
    title: "INTRODUCTION TO SOFT COMPUTING",
    moCode: "22MO0057",
    mgCode: "23MG0042",
    duration: "8",
  },
  {
    id: 162,
    title: "LITERATURE FOR COMPETITIVE EXAMS",
    moCode: "22MO0059",
    mgCode: null,
    duration: "8",
  },
  {
    id: 163,
    title: "NOVEL TECHNOLOGIES FOR FOOD PROCESSING AND SHELF LIFE EXTENSION",
    moCode: "22MO0060",
    mgCode: "24MG0069",
    duration: "12",
  },
  {
    id: 164,
    title: "NANOTECHNOLOGY, SCIENCE AND APPLICATIONS",
    moCode: "22MO0062",
    mgCode: null,
    duration: "8",
  },
  {
    id: 165,
    title: "A BRIEF INTRODUCTION OF MICRO - SENSORS",
    moCode: "22MO0063",
    mgCode: null,
    duration: "4",
  },
  {
    id: 166,
    title: "ADVANCED COMPUTER NETWORKS",
    moCode: "22MO0064",
    mgCode: null,
    duration: "12",
  },
  {
    id: 167,
    title: "ADVANCED DISTRIBUTED SYSTEMS",
    moCode: "22MO0065",
    mgCode: "23MG0043",
    duration: "12",
  },
  {
    id: 168,
    title: "ADVANCED NEURAL SCIENCE FOR ENGINEERS",
    moCode: "22MO0066",
    mgCode: null,
    duration: "12",
  },
  {
    id: 169,
    title: "AFFECTIVE COMPUTING",
    moCode: "22MO0067",
    mgCode: "24MG0012",
    duration: "12",
  },
  {
    id: 170,
    title: "AI:CONSTRAINT SATISFACTION",
    moCode: "22MO0068",
    mgCode: "23MG0044",
    duration: "8",
  },
  {
    id: 171,
    title: "ALGORITHMIC GAME THEORY",
    moCode: "22MO0069",
    mgCode: "24MG0091",
    duration: "12",
  },
  {
    id: 172,
    title: "ANALOG ELECTRONIC CIRCUITS",
    moCode: "22MO0070",
    mgCode: null,
    duration: "8",
  },
  {
    id: 173,
    title: "ANALYSIS AND DESIGN PRINCIPLES OF MICROWAVE ANTENNAS",
    moCode: "22MO0071",
    mgCode: null,
    duration: "8",
  },
  {
    id: 174,
    title: "APPLIED ACCELERATED ARTIFICIAL INTELLIGENCE",
    moCode: "22MO0073",
    mgCode: "23MG0045",
    duration: "12",
  },
  {
    id: 175,
    title: "APPLIED LINEAR ALGEBRA IN AI AND ML",
    moCode: "22MO0074",
    mgCode: null,
    duration: "12",
  },
  {
    id: 176,
    title: "ARTIFICIAL INTELLIGENCE SEARCH METHODS FOR PROBLEM SOLVING",
    moCode: "22MO0075",
    mgCode: null,
    duration: "12",
  },
  {
    id: 177,
    title: "ARTIFICIAL INTELLIGENCE: KNOWLEDGE REPRESENTATION AND REASONING",
    moCode: "22MO0076",
    mgCode: null,
    duration: "12",
  },
  {
    id: 178,
    title: "AUTOMATION IN MANUFACTURING",
    moCode: "22MO0077",
    mgCode: "24MG0116",
    duration: "12",
  },
  {
    id: 179,
    title: "BASIC CONSTRUCTION MATERIALS",
    moCode: "22MO0078",
    mgCode: null,
    duration: "12",
  },
  {
    id: 180,
    title: "BASICS OF BIOLOGY",
    moCode: "22MO0079",
    mgCode: null,
    duration: "12",
  },
  {
    id: 181,
    title: "BIOENGINEERING: AN INTERFACE WITH BIOLOGY AND MEDICINE",
    moCode: "22MO0080",
    mgCode: null,
    duration: "8",
  },
  {
    id: 182,
    title: "BIOINTERFACE ENGINEERING",
    moCode: "22MO0081",
    mgCode: "24MG0083",
    duration: "8",
  },
  {
    id: 183,
    title: "BIOMECHANICS",
    moCode: "22MO0082",
    mgCode: null,
    duration: "12",
  },
  {
    id: 184,
    title: "C-BASED VLSI DESIGN",
    moCode: "22MO0083",
    mgCode: "23MG0046",
    duration: "12",
  },
  {
    id: 185,
    title: "CIRCUIT COMPLEXITY THEORY",
    moCode: "22MO0084",
    mgCode: "24MG0013",
    duration: "12",
  },
  {
    id: 186,
    title: "CLOUD COMPUTING",
    moCode: "22MO0085",
    mgCode: "23MG0047",
    duration: "12",
  },
  {
    id: 187,
    title: "COMPUTATIONAL COMPLEXITY",
    moCode: "22MO0086",
    mgCode: "23MG0048",
    duration: "12",
  },
  {
    id: 188,
    title: "COMPUTATIONAL NUMBER THEORY AND ALGEBRA",
    moCode: "22MO0087",
    mgCode: null,
    duration: "12",
  },
  {
    id: 189,
    title: "COMPUTER GRAPHICS",
    moCode: "22MO0088",
    mgCode: "23MG0005",
    duration: "8",
  },
  {
    id: 190,
    title: "COMPUTER VISION",
    moCode: "22MO0089",
    mgCode: "23MG0049",
    duration: "12",
  },
  {
    id: 191,
    title: "CRYPTOGRAPHY AND NETWORK SECURITY",
    moCode: "22MO0090",
    mgCode: null,
    duration: "12",
  },
  {
    id: 192,
    title: "DATA STRUCTURE AND ALGORITHMS USING JAVA",
    moCode: "22MO0091",
    mgCode: null,
    duration: "12",
  },
  {
    id: 193,
    title: "DEMYSTIFYING NETWORKING",
    moCode: "22MO0092",
    mgCode: null,
    duration: "4",
  },
  {
    id: 194,
    title: "DESIGN & IMPLEMENTATION OF HUMAN-COMPUTER INTERFACES",
    moCode: "22MO0093",
    mgCode: "23MG0050",
    duration: "12",
  },
  {
    id: 195,
    title: "DESIGN OF REINFORCED CONCRETE STRUCTURES",
    moCode: "22MO0094",
    mgCode: null,
    duration: "12",
  },
  {
    id: 196,
    title: "DISTRIBUTED SYSTEMS",
    moCode: "22MO0095",
    mgCode: null,
    duration: "8",
  },
  {
    id: 197,
    title: "EMBEDDED SYSTEM DESIGN WITH ARM",
    moCode: "22MO0096",
    mgCode: "23MG0051",
    duration: "8",
  },
  {
    id: 198,
    title: "ENGLISH LITERATURE FOR COMPETITIVE EXAMS",
    moCode: "22MO0097",
    mgCode: null,
    duration: "8",
  },
  {
    id: 199,
    title: "FOUNDATION OF CLOUD IOT EDGE ML",
    moCode: "22MO0098",
    mgCode: "23MG0052",
    duration: "8",
  },
  {
    id: 200,
    title: "FOUNDATIONS OF CYBER PHYSICAL SYSTEMS",
    moCode: "22MO0099",
    mgCode: "24MG0014",
    duration: "12",
  },
  {
    id: 201,
    title: "FOUNDATIONS OF R SOFTWARE",
    moCode: "22MO0100",
    mgCode: "24MG0125",
    duration: "12",
  },
  {
    id: 202,
    title: "GENETIC ENGINEERING: THEORY AND APPLICATION",
    moCode: "22MO0101",
    mgCode: "23MG0006",
    duration: "12",
  },
  {
    id: 203,
    title: "GEOTECHNICAL ENGINEERING LABORATORY",
    moCode: "22MO0102",
    mgCode: null,
    duration: "4",
  },
  {
    id: 204,
    title: "GERMAN - III",
    moCode: "22MO0103",
    mgCode: "24MG0015",
    duration: "12",
  },
  {
    id: 205,
    title: "HARDWARE MODELING USING VERILOG",
    moCode: "22MO0104",
    mgCode: null,
    duration: "8",
  },
  {
    id: 206,
    title: "INTRODUCTION TO AIRBREATHING PROPULSION",
    moCode: "22MO0105",
    mgCode: null,
    duration: "12",
  },
  {
    id: 207,
    title: "INTRODUCTION TO CELL BIOLOGY",
    moCode: "22MO0106",
    mgCode: "24MG0016",
    duration: "8",
  },
  {
    id: 208,
    title:
      "INTRODUCTION TO COMPUTER AND NETWORK PERFORMANCE ANALYSIS USING QUEUING SYSTEMS",
    moCode: "22MO0107",
    mgCode: null,
    duration: "4",
  },
  {
    id: 209,
    title: "INTRODUCTION TO EMBEDDED SYSTEM DESIGN",
    moCode: "22MO0108",
    mgCode: null,
    duration: "12",
  },
  {
    id: 210,
    title: "INTRODUCTION TO FLUID MECHANICS",
    moCode: "22MO0109",
    mgCode: null,
    duration: "12",
  },
  {
    id: 211,
    title: "INTRODUCTION TO GAME THEORY AND MECHANISM DESIGN",
    moCode: "22MO0110",
    mgCode: "23MG0053",
    duration: "12",
  },
  {
    id: 212,
    title: "INTRODUCTION TO HASKELL PROGRAMMING",
    moCode: "22MO0111",
    mgCode: null,
    duration: "8",
  },
  {
    id: 213,
    title: "INTRODUCTION TO JAPANESE LANGUAGE AND CULTURE - II",
    moCode: "22MO0112",
    mgCode: "24MG0092",
    duration: "12",
  },
  {
    id: 214,
    title: "INTRODUCTION TO MACHINE LEARNING",
    moCode: "22MO0113",
    mgCode: "24MG0108",
    duration: "8",
  },
  {
    id: 215,
    title: "INTRODUCTION TO QUANTUM COMPUTING: QUANTUM ALGORITHMS AND QISKIT",
    moCode: "22MO0114",
    mgCode: "24MG0093",
    duration: "4",
  },
  {
    id: 216,
    title: "INTRODUCTION TO WIRELESS AND CELLULAR COMMUNICATIONS",
    moCode: "22MO0115",
    mgCode: null,
    duration: "12",
  },
  {
    id: 217,
    title: "LIGHTER THAN AIR SYSTEMS",
    moCode: "22MO0116",
    mgCode: null,
    duration: "12",
  },
  {
    id: 218,
    title: "MACHINE LEARNING FOR EARTH SYSTEM SCIENCES",
    moCode: "22MO0117",
    mgCode: "23MG0054",
    duration: "8",
  },
  {
    id: 219,
    title: "MECHANICS AND CONTROL OF ROBOTIC MANIPULATORS",
    moCode: "22MO0118",
    mgCode: null,
    duration: "8",
  },
  {
    id: 220,
    title: "MEDICAL IMAGE ANALYSIS",
    moCode: "22MO0119",
    mgCode: null,
    duration: "4",
  },
  {
    id: 221,
    title: "NATURAL LANGUAGE PROCESSING",
    moCode: "22MO0120",
    mgCode: "24MG0017",
    duration: "12",
  },
  {
    id: 222,
    title: "OBJECT ORIENTED ANALYSIS AND DESIGN",
    moCode: "22MO0121",
    mgCode: null,
    duration: "8",
  },
  {
    id: 223,
    title: "ORGAN PRINTING",
    moCode: "22MO0122",
    mgCode: "24MG0120",
    duration: "8",
  },
  {
    id: 224,
    title: "PARAMETERIZED ALGORITHMS",
    moCode: "22MO0123",
    mgCode: "23MG0055",
    duration: "12",
  },
  {
    id: 225,
    title: "PLASTIC WASTE MANAGEMENT",
    moCode: "22MO0124",
    mgCode: "24MG0018",
    duration: "8",
  },
  {
    id: 226,
    title:
      "POST HARVEST OPERATIONS AND PROCESSING OF FRUITS, VEGETABLES, SPICES AND PLANTATION CROP PRODUCTS",
    moCode: "22MO0125",
    mgCode: "24MG0118",
    duration: "12",
  },
  {
    id: 227,
    title: "PRIVACY AND SECURITY IN ONLINE SOCIAL MEDIA",
    moCode: "22MO0126",
    mgCode: "23MG0056",
    duration: "12",
  },
  {
    id: 228,
    title: "PRODUCT DESIGN AND DEVELOPMENT",
    moCode: "22MO0127",
    mgCode: null,
    duration: "4",
  },
  {
    id: 229,
    title: "PRODUCT ENGINEERING AND DESIGN THINKING",
    moCode: "22MO0128",
    mgCode: "23MG0003",
    duration: "8",
  },
  {
    id: 230,
    title: "QUANTUM ALGORITHMS AND CRYPTOGRAPHY",
    moCode: "22MO0129",
    mgCode: null,
    duration: "12",
  },
  {
    id: 231,
    title: "RANDOMIZED METHODS IN COMPLEXITY",
    moCode: "22MO0130",
    mgCode: "24MG0094",
    duration: "12",
  },
  {
    id: 232,
    title: "RAPID MANUFACTURING",
    moCode: "22MO0131",
    mgCode: "23MG0084",
    duration: "12",
  },
  {
    id: 233,
    title: "REAL-TIME SYSTEMS",
    moCode: "22MO0132",
    mgCode: null,
    duration: "12",
  },
  {
    id: 234,
    title: "ROCKET PROPULSION",
    moCode: "22MO0133",
    mgCode: null,
    duration: "12",
  },
  {
    id: 235,
    title: "SATELLITE ATTITUDE DYNAMICS AND CONTROL",
    moCode: "22MO0134",
    mgCode: null,
    duration: "12",
  },
  {
    id: 236,
    title: "SCALABLE DATA SCIENCE",
    moCode: "22MO0135",
    mgCode: null,
    duration: "8",
  },
  {
    id: 237,
    title: "SECURE COMPUTATION: PART I",
    moCode: "22MO0136",
    mgCode: "24MG0019",
    duration: "12",
  },
  {
    id: 238,
    title: "SECURE COMPUTATION: PART II",
    moCode: "22MO0137",
    mgCode: "23MG0057",
    duration: "12",
  },
  {
    id: 239,
    title: "SELECTED TOPICS IN ALGORITHMS",
    moCode: "22MO0138",
    mgCode: "24MG0020",
    duration: "12",
  },
  {
    id: 240,
    title: "SOFTWARE PROJECT MANAGEMENT",
    moCode: "22MO0139",
    mgCode: null,
    duration: "12",
  },
  {
    id: 241,
    title: "SPATIAL INFORMATICS",
    moCode: "22MO0140",
    mgCode: null,
    duration: "8",
  },
  {
    id: 242,
    title: "STATISTICAL LEARNING FOR RELIABILITY ANALYSIS",
    moCode: "22MO0141",
    mgCode: "23MG0058",
    duration: "12",
  },
  {
    id: 243,
    title: "UNDERSTANDING DESIGN",
    moCode: "22MO0142",
    mgCode: null,
    duration: "4",
  },
  {
    id: 244,
    title: "USER-CENTRIC COMPUTING FOR HUMAN-COMPUTER INTERACTION",
    moCode: "22MO0143",
    mgCode: "23MG0059",
    duration: "8",
  },
  {
    id: 245,
    title: "AUTOMATIC CONTROL",
    moCode: "22MO0144",
    mgCode: "24MG0021",
    duration: "8",
  },
  {
    id: 246,
    title: "SYSTEM DESIGN THROUGH VERILOG",
    moCode: "22MO0145",
    mgCode: "24MG0109",
    duration: "8",
  },
  {
    id: 247,
    title: "SOLAR ENERGY ENGINEERING AND TECHNOLOGY",
    moCode: "22MO0146",
    mgCode: null,
    duration: "12",
  },
  {
    id: 248,
    title: "ADVANCES IN STRATEGIC HUMAN RESOURCE MANAGEMENT (HRM)",
    moCode: "22MO0147",
    mgCode: null,
    duration: "4",
  },
  {
    id: 249,
    title: "BUSINESS STATISTICS",
    moCode: "22MO0148",
    mgCode: null,
    duration: "12",
  },
  {
    id: 250,
    title: "DIGITAL MARKETING",
    moCode: "22MO0149",
    mgCode: null,
    duration: "15",
  },
  {
    id: 251,
    title: "E-COMMERCE",
    moCode: "22MO0150",
    mgCode: null,
    duration: "12",
  },
  {
    id: 252,
    title: "EFFECTIVE BUSINESS COMMUNICATION",
    moCode: "22MO0151",
    mgCode: null,
    duration: "6",
  },
  {
    id: 253,
    title: "HUMAN RESOURCE MANAGEMENT",
    moCode: "22MO0152",
    mgCode: null,
    duration: "12",
  },
  {
    id: 254,
    title: "INTERNATIONAL MARKETING",
    moCode: "22MO0153",
    mgCode: "23MG0086",
    duration: "8",
  },
  {
    id: 255,
    title: "INTRODUCTION TO BANKING AND FINANCIAL MARKETS",
    moCode: "22MO0154",
    mgCode: null,
    duration: "4",
  },
  {
    id: 256,
    title: "INVESTMENT MANAGEMENT",
    moCode: "22MO0155",
    mgCode: "23MG0087",
    duration: "8",
  },
  {
    id: 257,
    title: "MARKETING MANAGEMENT - II",
    moCode: "22MO0156",
    mgCode: "23MG0088",
    duration: "8",
  },
  {
    id: 258,
    title: "MS 2: MANAGEMENT OF HUMAN RESOURCES",
    moCode: "22MO0157",
    mgCode: null,
    duration: "16",
  },
  {
    id: 259,
    title: "QUALITY CONTROL AND IMPROVEMENT WITH MINITAB",
    moCode: "22MO0158",
    mgCode: null,
    duration: "8",
  },
  {
    id: 260,
    title: "SALES AND DISTRIBUTION MANAGEMENT",
    moCode: "22MO0159",
    mgCode: null,
    duration: "8",
  },
  {
    id: 261,
    title: "SUPPLY CHAIN ANALYTICS",
    moCode: "22MO0160",
    mgCode: null,
    duration: "8",
  },
  {
    id: 262,
    title: "PLANT DEVELOPMENTAL BIOLOGY",
    moCode: "22MO0161",
    mgCode: "24MG0060",
    duration: "4",
  },
  {
    id: 263,
    title: "COMPUTATIONAL SCIENCE IN ENGINEERING",
    moCode: "22MO0162",
    mgCode: null,
    duration: "8",
  },
  {
    id: 264,
    title: "LAWS OF THERMODYNAMICS",
    moCode: "22MO0163",
    mgCode: null,
    duration: "4",
  },
  {
    id: 265,
    title: "ELASTIC STABILITY OF STRUCTURES",
    moCode: "22MO0164",
    mgCode: null,
    duration: "12",
  },
  {
    id: 266,
    title:
      "COOLING TECHNOLOGY: WHY AND HOW UTILIZED IN FOOD PROCESSING AND ALLIED INDUSTRIES",
    moCode: "22MO0165",
    mgCode: "24MG0022",
    duration: "12",
  },
  {
    id: 267,
    title: "THE PSYCHOLOGY OF LANGUAGE",
    moCode: "22MO0166",
    mgCode: "23MG0016",
    duration: "8",
  },
  {
    id: 268,
    title: "INTRODUCTION TO ADVANCED COGNITIVE PROCESSES",
    moCode: "22MO0167",
    mgCode: "23MG0017",
    duration: "8",
  },
  {
    id: 269,
    title: "AN INTRODUCTION TO INDIAN LITERARY THEORY",
    moCode: "22MO0168",
    mgCode: null,
    duration: "8",
  },
  {
    id: 270,
    title: "PROFICIENCY COURSE IN FRENCH",
    moCode: "22MO0172",
    mgCode: null,
    duration: "12",
  },
  {
    id: 271,
    title: "REAL TIME OPERATING SYSTEM",
    moCode: "22MO0173",
    mgCode: null,
    duration: "4",
  },
  {
    id: 272,
    title: "ADVANCED ROBOTICS",
    moCode: "23MO0001",
    mgCode: null,
    duration: "12",
  },
  {
    id: 273,
    title: "AIR POLLUTION AND CONTROL",
    moCode: "23MO0002",
    mgCode: "24MG0023",
    duration: "12",
  },
  {
    id: 274,
    title: "ANDROID MOBILE APPLICATION DEVELOPMENT",
    moCode: "23MO0003",
    mgCode: null,
    duration: "12",
  },
  {
    id: 275,
    title: "BASIC ELECTRONICS",
    moCode: "23MO0004",
    mgCode: null,
    duration: "12",
  },
  {
    id: 276,
    title: "BASICS OF MENTAL HEALTH & CLINICAL PSYCHIATRY",
    moCode: "23MO0005",
    mgCode: null,
    duration: "8",
  },
  {
    id: 277,
    title: "BIOLOGICAL PROCESS DESIGN FOR WASTEWATER TREATMENT",
    moCode: "23MO0006",
    mgCode: "23MG0093",
    duration: "8",
  },
  {
    id: 278,
    title: "BRAND MANAGEMENT",
    moCode: "23MO0007",
    mgCode: "24MG0024",
    duration: "8",
  },
  {
    id: 279,
    title: "BUSINESS ANALYTICS & TEXT MINING MODELING USING PYTHON",
    moCode: "23MO0008",
    mgCode: null,
    duration: "8",
  },
  {
    id: 280,
    title: "BUSINESS TO BUSINESS MARKETING (B2B)",
    moCode: "23MO0009",
    mgCode: "24MG0025",
    duration: "12",
  },
  {
    id: 281,
    title: "COMMUNICATION NETWORKS",
    moCode: "23MO0011",
    mgCode: null,
    duration: "12",
  },
  {
    id: 282,
    title: "DATA BASE MANAGEMENT SYSTEM",
    moCode: "23MO0012",
    mgCode: "24MG0026",
    duration: "8",
  },
  {
    id: 283,
    title: "DATA SCIENCE FOR ENGINEERS",
    moCode: "23MO0013",
    mgCode: "23MG0060",
    duration: "8",
  },
  {
    id: 284,
    title: "DEVELOPMENT AND APPLICATIONS OF SPECIAL CONCRETES",
    moCode: "23MO0014",
    mgCode: null,
    duration: "8",
  },
  {
    id: 285,
    title: "DRUG DELIVERY: PRINCIPLES AND ENGINEERING",
    moCode: "23MO0015",
    mgCode: null,
    duration: "12",
  },
  {
    id: 286,
    title: "ELECTRONIC SYSTEMS FOR CANCER DIAGNOSIS",
    moCode: "23MO0016",
    mgCode: "24MG0078",
    duration: "12",
  },
  {
    id: 287,
    title: "ELECTRONIC WASTE MANAGEMENT - ISSUES AND CHALLENGES",
    moCode: "23MO0017",
    mgCode: null,
    duration: "4",
  },
  {
    id: 288,
    title: "ENGINEERING STATISTICS",
    moCode: "23MO0018",
    mgCode: "23MG0004",
    duration: "12",
  },
  {
    id: 289,
    title: "ENTREPRENEURSHIP",
    moCode: "23MO0019",
    mgCode: null,
    duration: "12",
  },
  {
    id: 290,
    title: "FINANCIAL ACCOUNTING",
    moCode: "23MO0020",
    mgCode: "23MG0018",
    duration: "8",
  },
  {
    id: 291,
    title: "FUZZY LOGIC AND NEURAL NETWORKS",
    moCode: "23MO0021",
    mgCode: null,
    duration: "8",
  },
  {
    id: 292,
    title: "GRAPH THEORY",
    moCode: "23MO0022",
    mgCode: null,
    duration: "8",
  },
  {
    id: 293,
    title: "INDIAN KNOWLEDGE SYSTEM(IKS): HUMANITIES AND SOCIAL SCIENCES",
    moCode: "23MO0023",
    mgCode: null,
    duration: "10",
  },
  {
    id: 294,
    title: "INNOVATION BY DESIGN",
    moCode: "23MO0024",
    mgCode: null,
    duration: "4",
  },
  {
    id: 295,
    title: "INTRODUCTION TO MACHINE LEARNING",
    moCode: "23MO0025",
    mgCode: "23MG0069",
    duration: "12",
  },
  {
    id: 296,
    title: "INTRODUCTION TO MECHANICAL MICRO MACHINING",
    moCode: "23MO0026",
    mgCode: null,
    duration: "12",
  },
  {
    id: 297,
    title: "MACHINE LEARNING,ML",
    moCode: "23MO0027",
    mgCode: null,
    duration: "8",
  },
  {
    id: 298,
    title: "MARKETING MANAGEMENT - I",
    moCode: "23MO0028",
    mgCode: null,
    duration: "8",
  },
  {
    id: 299,
    title: "MATERNAL INFANT YOUNG CHILD NUTRITION",
    moCode: "23MO0029",
    mgCode: "24MG0027",
    duration: "12",
  },
  {
    id: 300,
    title: "MECHATRONICS",
    moCode: "23MO0030",
    mgCode: "24MG0066",
    duration: "8",
  },
  {
    id: 301,
    title: "METABOLIC ENGINEERING",
    moCode: "23MO0031",
    mgCode: null,
    duration: "8",
  },
  {
    id: 302,
    title: "NATURAL HAZARDS",
    moCode: "23MO0032",
    mgCode: "24MG0028",
    duration: "8",
  },
  {
    id: 303,
    title: "OPERATIONS AND SUPPLY CHAIN MANAGEMENT",
    moCode: "23MO0033",
    mgCode: null,
    duration: "12",
  },
  {
    id: 304,
    title: "PRINCIPLES OF MANAGEMENT",
    moCode: "23MO0034",
    mgCode: null,
    duration: "12",
  },
  {
    id: 305,
    title: "PRODUCT AND BRAND MANAGEMENT",
    moCode: "23MO0035",
    mgCode: null,
    duration: "12",
  },
  {
    id: 306,
    title: "PROJECT MANAGEMENT",
    moCode: "23MO0036",
    mgCode: null,
    duration: "8",
  },
  {
    id: 307,
    title: "PROJECT MANAGEMENT : PLANNING, EXECUTION, EVALUATION AND CONTROL",
    moCode: "23MO0037",
    mgCode: null,
    duration: "8",
  },
  {
    id: 308,
    title: "SIGNAL PROCESSING TECHNIQUES AND ITS APPLICATIONS",
    moCode: "23MO0038",
    mgCode: null,
    duration: "12",
  },
  {
    id: 309,
    title: "SOIL AND WATER CONSERVATION ENGINEERING",
    moCode: "23MO0039",
    mgCode: null,
    duration: "12",
  },
  {
    id: 310,
    title: "STRATEGIES FOR SUSTAINABLE DESIGN",
    moCode: "23MO0040",
    mgCode: null,
    duration: "12",
  },
  {
    id: 311,
    title: "TOWARDS AN ETHICAL DIGITAL SOCIETY: FROM THEORY TO PRACTICE",
    moCode: "23MO0041",
    mgCode: null,
    duration: "4",
  },
  {
    id: 312,
    title: "TOYOTA PRODUCTION SYSTEM",
    moCode: "23MO0042",
    mgCode: "23MG0089",
    duration: "8",
  },
  {
    id: 313,
    title: "URBAN SERVICES PLANNING",
    moCode: "23MO0043",
    mgCode: null,
    duration: "12",
  },
  {
    id: 314,
    title: "WHEELED MOBILE ROBOTS",
    moCode: "23MO0044",
    mgCode: "24MG0067",
    duration: "8",
  },
  {
    id: 315,
    title: "MUNICIPAL SOLID WASTE MANAGEMENT",
    moCode: "23MO0045",
    mgCode: "24MG0086",
    duration: "12",
  },
  {
    id: 316,
    title: "ASPEN PLUS SIMULATION SOFTWARE - A BASIC COURSE FOR BEGINNERS",
    moCode: "23MO0046",
    mgCode: null,
    duration: "12",
  },
  {
    id: 317,
    title: "ENERGY CONVERSION TECHNOLOGIES (BIOMASS AND COAL)",
    moCode: "23MO0047",
    mgCode: null,
    duration: "8",
  },
  {
    id: 318,
    title:
      "NEXT GENERATION SEQUENCING TECHNOLOGIES : DATA ANALYSIS AND APPLICATIONS",
    moCode: "23MO0048",
    mgCode: null,
    duration: "12",
  },
  {
    id: 319,
    title: "INTRODUCTION TO PROTEOGENOMICS",
    moCode: "23MO0049",
    mgCode: null,
    duration: "12",
  },
  {
    id: 320,
    title: "CELLULAR BIOPHYSICS: A FRAMEWORK FOR QUANTITATIVE BIOLOGY",
    moCode: "23MO0050",
    mgCode: null,
    duration: "8",
  },
  {
    id: 321,
    title: "MEDICAL IMAGE ANALYSIS",
    moCode: "23MO0051",
    mgCode: null,
    duration: "12",
  },
  {
    id: 322,
    title: "PRINCIPLES OF DOWNSTREAM TECHNIQUES IN BIOPROCESS",
    moCode: "23MO0052",
    mgCode: null,
    duration: "12",
  },
  {
    id: 323,
    title: "TRANSPORT PHENOMENA IN BIOLOGICAL SYSTEMS",
    moCode: "23MO0053",
    mgCode: null,
    duration: "12",
  },
  {
    id: 324,
    title: "INTRODUCTION TO BIOMEDICAL IMAGING SYSTEMS",
    moCode: "23MO0054",
    mgCode: null,
    duration: "12",
  },
  {
    id: 325,
    title: "GENOME EDITING AND ENGINEERING",
    moCode: "23MO0055",
    mgCode: "24MG0061",
    duration: "12",
  },
  {
    id: 326,
    title: "INTRODUCTION TO DYNAMICAL MODELS IN BIOLOGY",
    moCode: "23MO0056",
    mgCode: null,
    duration: "4",
  },
  {
    id: 327,
    title: "FUNCTIONAL GENOMICS",
    moCode: "23MO0057",
    mgCode: null,
    duration: "4",
  },
  {
    id: 328,
    title: "EXPERIMENTAL BIOTECHNOLOGY",
    moCode: "23MO0058",
    mgCode: "23MG0010",
    duration: "12",
  },
  {
    id: 329,
    title: "INTRODUCTION TO MECHANOBIOLOGY",
    moCode: "23MO0059",
    mgCode: "24MG0113",
    duration: "8",
  },
  {
    id: 330,
    title: "INTRODUCTION TO PROTEOMICS",
    moCode: "23MO0060",
    mgCode: null,
    duration: "8",
  },
  {
    id: 331,
    title: "COMPUTATIONAL NEUROSCIENCE",
    moCode: "23MO0061",
    mgCode: null,
    duration: "12",
  },
  {
    id: 332,
    title: "NEUROBIOLOGY",
    moCode: "23MO0062",
    mgCode: null,
    duration: "4",
  },
  {
    id: 333,
    title: "RNA BIOLOGY",
    moCode: "23MO0063",
    mgCode: null,
    duration: "12",
  },
  {
    id: 334,
    title: "HOST-PATHOGEN INTERACTION (IMMUNOLOGY)",
    moCode: "23MO0064",
    mgCode: "23MG0012",
    duration: "12",
  },
  {
    id: 335,
    title: "PSYCHOLOGY OF LEARNING",
    moCode: "23MO0065",
    mgCode: "23MG0081",
    duration: "12",
  },
  {
    id: 336,
    title: "YOGA AND POSITIVE PSYCHOLOGY FOR MANAGING CAREER AND LIFE",
    moCode: "23MO0066",
    mgCode: "23MG0019",
    duration: "8",
  },
  {
    id: 337,
    title: "ADVANCE COURSE IN SOCIAL PSYCHOLOGY",
    moCode: "23MO0067",
    mgCode: "23MG0082",
    duration: "12",
  },
  {
    id: 338,
    title: "DESIGN, TECHNOLOGY AND INNOVATION",
    moCode: "23MO0068",
    mgCode: "23MG0001",
    duration: "8",
  },
  {
    id: 339,
    title: "COUNTERING STAGE FRIGHT",
    moCode: "23MO0069",
    mgCode: null,
    duration: "4",
  },
  {
    id: 340,
    title: "ROBOTICS",
    moCode: "23MO0070",
    mgCode: "24MG0068",
    duration: "8",
  },
  {
    id: 341,
    title: "FOOD PACKAGING TECHNOLOGY",
    moCode: "23MO0071",
    mgCode: "23MG0075",
    duration: "8",
  },
  {
    id: 342,
    title: "GENDER AND LITERATURE",
    moCode: "23MO0072",
    mgCode: null,
    duration: "8",
  },
  {
    id: 343,
    title: "FOUNDATIONS OF COGNITIVE ROBOTICS",
    moCode: "23MO0073",
    mgCode: null,
    duration: "4",
  },
  {
    id: 344,
    title: "PRODUCT DESIGN AND MANUFACTURING",
    moCode: "23MO0074",
    mgCode: "24MG0056",
    duration: "12",
  },
  {
    id: 345,
    title: "ENTREPRENEURSHIP AND IP STRATEGY",
    moCode: "23MO0075",
    mgCode: null,
    duration: "8",
  },
  {
    id: 346,
    title: "CYBER SECURITY AND PRIVACY",
    moCode: "23MO0076",
    mgCode: "23MG0020",
    duration: "12",
  },
  {
    id: 347,
    title: "SENSOR TECHNOLOGIES: PHYSICS, FABRICATION, AND CIRCUITS",
    moCode: "23MO0077",
    mgCode: "24MG0110",
    duration: "8",
  },
  {
    id: 348,
    title: "OPERATING SYSTEM FUNDAMENTALS",
    moCode: "23MO0078",
    mgCode: null,
    duration: "12",
  },
  {
    id: 349,
    title: "INTRODUCTION TO OPERATING SYSTEMS",
    moCode: "23MO0079",
    mgCode: "24MG0079",
    duration: "8",
  },
  {
    id: 350,
    title: "ADVANCE POWER ELECTRONICS AND CONTROL",
    moCode: "23MO0080",
    mgCode: "24MG0126",
    duration: "8",
  },
  {
    id: 351,
    title: "ADVANCES IN UHV TRANSMISSION AND DISTRIBUTION",
    moCode: "23MO0081",
    mgCode: null,
    duration: "8",
  },
  {
    id: 352,
    title: "ANALOG COMMUNICATION",
    moCode: "23MO0082",
    mgCode: null,
    duration: "12",
  },
  {
    id: 353,
    title: "CUSTOMER RELATIONSHIP MANAGEMENT",
    moCode: "23MO0083",
    mgCode: "23MG0090",
    duration: "8",
  },
  {
    id: 354,
    title: "MODERN INDIAN ARCHITECTURE",
    moCode: "23MO0084",
    mgCode: "23MG0021",
    duration: "8",
  },
  {
    id: 355,
    title: "ECOLOGY AND ENVIRONMENT",
    moCode: "23MO0085",
    mgCode: "23MG0022",
    duration: "8",
  },
  {
    id: 356,
    title: "THE SCIENCE OF HAPPINESS AND WELLBEING",
    moCode: "23MO0086",
    mgCode: "23MG0023",
    duration: "8",
  },
  {
    id: 357,
    title: "BODY LANGUAGE: KEY TO PROFESSIONAL SUCCESS",
    moCode: "23MO0087",
    mgCode: "23MG0024",
    duration: "4",
  },
  {
    id: 358,
    title: "PSYCHOLOGY OF EVERYDAY",
    moCode: "23MO0088",
    mgCode: "23MG0025",
    duration: "4",
  },
  {
    id: 359,
    title: "FORENSIC LINGUISTICS",
    moCode: "23MO0089",
    mgCode: "24MG0029",
    duration: "4",
  },
  {
    id: 360,
    title: "CELL BIOLOGY: CELLULAR ORGANIZATION, DIVISION AND PROCESSES",
    moCode: "23MO0090",
    mgCode: "23MG0092",
    duration: "8",
  },
  {
    id: 361,
    title: "SOFT SKILL DEVELOPMENT",
    moCode: "23MO0091",
    mgCode: "23MG0026",
    duration: "8",
  },
  {
    id: 362,
    title: "ENHANCING SOFT SKILLS AND PERSONALITY",
    moCode: "23MO0092",
    mgCode: "24MG0030",
    duration: "8",
  },
  {
    id: 363,
    title: "ORAL BIOLOGY",
    moCode: "23MO0093",
    mgCode: null,
    duration: "8",
  },
  {
    id: 364,
    title: "INTRODUCTION TO PROGRAMMING IN C",
    moCode: "23MO0094",
    mgCode: "24MG0031",
    duration: "8",
  },
  {
    id: 365,
    title: "RESEARCH METHODOLOGY",
    moCode: "23MO0095",
    mgCode: "24MG0124",
    duration: "8",
  },
  {
    id: 366,
    title: "CONSTITUTIONAL GOVERNMENT & DEMOCRACY IN INDIA",
    moCode: "23MO0096",
    mgCode: null,
    duration: "15",
  },
  {
    id: 367,
    title: "SPORTS AND PERFORMANCE NUTRITION",
    moCode: "23MO0097",
    mgCode: "24MG0032",
    duration: "8",
  },
  {
    id: 368,
    title: "HUMAN MOVEMENT SCIENCE",
    moCode: "23MO0098",
    mgCode: "24MG0084",
    duration: "8",
  },
  {
    id: 369,
    title: "INTELLECTUAL PROPERTY",
    moCode: "23MO0099",
    mgCode: null,
    duration: "12",
  },
  {
    id: 370,
    title: "ENTREPRENEURSHIP ESSENTIALS",
    moCode: "23MO0100",
    mgCode: null,
    duration: "12",
  },
  {
    id: 371,
    title: "PSYCHIATRY - AN OVERVIEW AND HOW THE BRAIN CREATES MIND",
    moCode: "23MO0101",
    mgCode: "24MG0033",
    duration: "8",
  },
  {
    id: 372,
    title: "CENTRE-STATE RELATIONS IN INDIA",
    moCode: "23MO0102",
    mgCode: null,
    duration: "8",
  },
  {
    id: 373,
    title: "CONSUMER PSYCHOLOGY",
    moCode: "23MO0103",
    mgCode: "23MG0027",
    duration: "8",
  },
  {
    id: 374,
    title: "BUSINESS LAW FOR MANAGERS",
    moCode: "23MO0104",
    mgCode: null,
    duration: "8",
  },
  {
    id: 375,
    title: "STRATEGIC MANAGEMENT – THE COMPETITIVE EDGE",
    moCode: "23MO0105",
    mgCode: "23MG0028",
    duration: "8",
  },
  {
    id: 376,
    title: "CONSUMER BEHAVIOUR",
    moCode: "23MO0106",
    mgCode: "23MG0029",
    duration: "8",
  },
  {
    id: 377,
    title: "GOOGLE CLOUD COMPUTING FOUNDATIONS",
    moCode: "23MO0107",
    mgCode: "23MG0061",
    duration: "8",
  },
  {
    id: 378,
    title: "MODERN ALGEBRA",
    moCode: "23MO0108",
    mgCode: "23MG0062",
    duration: "8",
  },
  {
    id: 379,
    title: "MULTI-CORE COMPUTER ARCHITECTURE",
    moCode: "23MO0109",
    mgCode: "23MG0063",
    duration: "12",
  },
  {
    id: 380,
    title: "DESIGN AND ANALYSIS OF ALGORITHMS",
    moCode: "23MO0110",
    mgCode: "23MG0064",
    duration: "8",
  },
  {
    id: 381,
    title: "SOFTWARE TESTING",
    moCode: "23MO0111",
    mgCode: "23MG0065",
    duration: "4",
  },
  {
    id: 382,
    title: "EDGE COMPUTING",
    moCode: "23MO0112",
    mgCode: "23MG0066",
    duration: "8",
  },
  {
    id: 383,
    title: "LINEAR PROGRAMMING AND ITS APPLICATIONS TO COMPUTER SCIENCE",
    moCode: "23MO0113",
    mgCode: "23MG0067",
    duration: "8",
  },
  {
    id: 384,
    title: "BASIC ENVIRONMENTAL ENGINEERING AND POLLUTION ABATEMENT",
    moCode: "23MO0114",
    mgCode: "24MG0127",
    duration: "12",
  },
  {
    id: 385,
    title: "SMART STRUCTURES",
    moCode: "23MO0115",
    mgCode: "23MG0070",
    duration: "12",
  },
  {
    id: 386,
    title: "CORPORATE SOCIAL RESPONSIBILITY",
    moCode: "23MO0116",
    mgCode: null,
    duration: "8",
  },
  {
    id: 387,
    title: "DESIGN OF FIXED WING UNMANNED AERIAL VEHICLES",
    moCode: "23MO0117",
    mgCode: null,
    duration: "8",
  },
  {
    id: 388,
    title: "ENVIRONMENT AND DEVELOPMENT",
    moCode: "23MO0118",
    mgCode: null,
    duration: "12",
  },
  {
    id: 389,
    title: "FUNDAMENTALS OF ADDITIVE MANUFACTURING TECHNOLOGIES",
    moCode: "23MO0119",
    mgCode: null,
    duration: "12",
  },
  {
    id: 390,
    title: "FUNDAMENTALS OF MANUFACTURING PROCESSES",
    moCode: "23MO0120",
    mgCode: null,
    duration: "12",
  },
  {
    id: 391,
    title: "GLOBAL NAVIGATION SATELLITE SYSTEMS AND APPLICATIONS",
    moCode: "23MO0121",
    mgCode: null,
    duration: "4",
  },
  {
    id: 392,
    title: "INTRODUCTION TO COMPOSITES",
    moCode: "23MO0122",
    mgCode: null,
    duration: "12",
  },
  {
    id: 393,
    title: "INTRODUCTION TO MARKETING ESSENTIALS",
    moCode: "23MO0123",
    mgCode: "23MG0071",
    duration: "12",
  },
  {
    id: 394,
    title: "KNOWLEDGE MANAGEMENT",
    moCode: "23MO0124",
    mgCode: null,
    duration: "8",
  },
  {
    id: 395,
    title: "MECHANICAL BEHAVIOR OF POLYMERS AND COMPOSITES",
    moCode: "23MO0125",
    mgCode: null,
    duration: "12",
  },
  {
    id: 396,
    title: "METAL ADDITIVE MANUFACTURING",
    moCode: "23MO0126",
    mgCode: "24MG0117",
    duration: "12",
  },
  {
    id: 397,
    title: "NATURAL RESOURCES MANAGEMENT",
    moCode: "23MO0127",
    mgCode: null,
    duration: "12",
  },
  {
    id: 398,
    title: "ORGANIC FARMING FOR SUSTAINABLE AGRICULTURAL PRODUCTION",
    moCode: "23MO0128",
    mgCode: null,
    duration: "8",
  },
  {
    id: 399,
    title: "POSTMODERNISM IN LITERATURE",
    moCode: "23MO0129",
    mgCode: null,
    duration: "8",
  },
  {
    id: 400,
    title: "PUBLIC SPEAKING",
    moCode: "23MO0130",
    mgCode: "23MG0072",
    duration: "12",
  },
  {
    id: 401,
    title: "SUSTAINABLE ENGINEERING CONCEPTS AND LIFE CYCLE ANALYSIS",
    moCode: "23MO0131",
    mgCode: "24MG0123",
    duration: "8",
  },
  {
    id: 402,
    title: "VIBRATION AND STRUCTURAL DYNAMICS",
    moCode: "23MO0132",
    mgCode: null,
    duration: "8",
  },
  {
    id: 403,
    title: "SOCIAL INNOVATION IN INDUSTRY 4.0",
    moCode: "23MO0133",
    mgCode: null,
    duration: "12",
  },
  {
    id: 404,
    title: "INDUSTRIAL ROBOTICS : THEORIES FOR IMPLEMENTATION",
    moCode: "23MO0134",
    mgCode: null,
    duration: "12",
  },
  {
    id: 405,
    title: "LASER BASED MANUFACTURING",
    moCode: "23MO0135",
    mgCode: "24MG0129",
    duration: "8",
  },
  {
    id: 406,
    title:
      "THERMAL OPERATIONS IN FOOD PROCESS ENGINEERING: THEORY AND APPLICATIONS",
    moCode: "23MO0136",
    mgCode: null,
    duration: "12",
  },
  {
    id: 407,
    title: "CANNING TECHNOLOGY, VALUE ADDITION OF SEAFOOD (FISH PROCESSING)",
    moCode: "23MO0137",
    mgCode: "23MG0076",
    duration: "8",
  },
  {
    id: 408,
    title: "ADVANCED AQUACULTURE TECHNOLOGY",
    moCode: "23MO0138",
    mgCode: "23MG0077",
    duration: "12",
  },
  {
    id: 409,
    title: "BUILDING MATERIALS AND COMPOSITES",
    moCode: "23MO0139",
    mgCode: null,
    duration: "8",
  },
  {
    id: 410,
    title: "INTEGRATED WASTE MANAGEMENT FOR A SMART CITY",
    moCode: "23MO0140",
    mgCode: null,
    duration: "12",
  },
  {
    id: 411,
    title: "PROJECT PLANNING & CONTROL",
    moCode: "23MO0141",
    mgCode: null,
    duration: "8",
  },
  {
    id: 412,
    title: "COMPUTATIONAL GENOMICS",
    moCode: "23MO0142",
    mgCode: null,
    duration: "12",
  },
  {
    id: 413,
    title: "HUMAN PHYSIOLOGY",
    moCode: "23MO0143",
    mgCode: null,
    duration: "12",
  },
  {
    id: 414,
    title: "PHARMACOGNOSY & METABOLIC ENGINEERING",
    moCode: "23MO0144",
    mgCode: null,
    duration: "12",
  },
  {
    id: 415,
    title: "DATA ANALYSIS FOR BIOLOGISTS",
    moCode: "23MO0145",
    mgCode: "24MG0062",
    duration: "8",
  },
  {
    id: 416,
    title: "INTERACTOMICS : BASICS & APPLICATIONS",
    moCode: "23MO0146",
    mgCode: null,
    duration: "12",
  },
  {
    id: 417,
    title:
      "THERMODYNAMICS FOR BIOLOGICAL SYSTEMS : CLASSICAL AND STATISTICAL ASPECTS",
    moCode: "23MO0147",
    mgCode: null,
    duration: "12",
  },
  {
    id: 418,
    title:
      "OPTICAL SPECTROSCOPY AND MICROSCOPY : FUNDAMENTALS OF OPTICAL MEASUREMENTS AND INSTRUMENTATION",
    moCode: "23MO0148",
    mgCode: null,
    duration: "12",
  },
  {
    id: 419,
    title: "BIOSTATISTICS AND DESIGN OF EXPERIMENTS",
    moCode: "23MO0149",
    mgCode: null,
    duration: "8",
  },
  {
    id: 420,
    title: "FOUNDATION OF R SOFTWARE",
    moCode: "23MO0150",
    mgCode: null,
    duration: "12",
  },
  {
    id: 421,
    title: "MACHINE LEARNING AND DEEP LEARNING - FUNDAMENTALS AND APPLICATIONS",
    moCode: "23MO0151",
    mgCode: "23MG0080",
    duration: "12",
  },
  {
    id: 422,
    title:
      "APPLIED LINEAR ALGEBRA FOR SIGNAL PROCESSING, DATA ANALYTICS AND MACHINE LEARNING",
    moCode: "23MO0152",
    mgCode: null,
    duration: "12",
  },
  {
    id: 423,
    title: "E-BUSINESS",
    moCode: "23MO0153",
    mgCode: null,
    duration: "12",
  },
  {
    id: 424,
    title: "NEURAL SCIENCE FOR ENGINEERS",
    moCode: "23MO0154",
    mgCode: null,
    duration: "12",
  },
  {
    id: 425,
    title: "SCIENTIFIC COMPUTING USING PYTHON",
    moCode: "23MO0155",
    mgCode: "23MG0083",
    duration: "12",
  },
  {
    id: 426,
    title: "I THINK BIOLOGY",
    moCode: "23MO0156",
    mgCode: null,
    duration: "12",
  },
  {
    id: 427,
    title: "BIOMECHANICS OF JOINTS AND ORTHOPAEDIC IMPLANTS",
    moCode: "23MO0157",
    mgCode: null,
    duration: "8",
  },
  {
    id: 428,
    title: "NON-CONVENTIONAL ENERGY RESOURCES",
    moCode: "23MO0158",
    mgCode: null,
    duration: "12",
  },
  {
    id: 429,
    title: "MEDICAL LAW",
    moCode: "23MO0159",
    mgCode: null,
    duration: "8",
  },
  {
    id: 430,
    title: "ROADMAP FOR PATENT CREATION",
    moCode: "23MO0160",
    mgCode: null,
    duration: "8",
  },
  {
    id: 431,
    title: "BUSINESS ANALYTICS FOR MANAGEMENT DECISION",
    moCode: "23MO0161",
    mgCode: null,
    duration: "12",
  },
  {
    id: 432,
    title: "INTRODUCTION TO ANCIENT INDIAN TECHNOLOGY",
    moCode: "23MO0162",
    mgCode: null,
    duration: "8",
  },
  {
    id: 433,
    title: "UNDERSTANDING ETHNOGRAPHY",
    moCode: "23MO0163",
    mgCode: null,
    duration: "8",
  },
  {
    id: 434,
    title: "BASIC LINEAR ALGEBRA",
    moCode: "23MO0164",
    mgCode: null,
    duration: "8",
  },
  {
    id: 435,
    title: "WASTE TO ENERGY CONVERSION",
    moCode: "23MO0165",
    mgCode: "24MG0131",
    duration: "8",
  },
  {
    id: 436,
    title: "EFFECTIVE WRITING",
    moCode: "23MO0166",
    mgCode: null,
    duration: "4",
  },
  {
    id: 437,
    title: "INSPECTION AND QUALITY CONTROL IN MANUFACTURING",
    moCode: "23MO0167",
    mgCode: null,
    duration: "4",
  },
  {
    id: 438,
    title: "SURFACE ENGINEERING OF NANOMATERIALS",
    moCode: "23MO0168",
    mgCode: null,
    duration: "8",
  },
  {
    id: 439,
    title: "MANUFACTURING GUIDELINES FOR PRODUCT DESIGN",
    moCode: "23MO0169",
    mgCode: null,
    duration: "8",
  },
  {
    id: 440,
    title: "INTEGRATED MARKETING MANAGEMENT",
    moCode: "23MO0171",
    mgCode: "23MG0094",
    duration: "8",
  },
  {
    id: 441,
    title: "RETAIL MANAGEMENT",
    moCode: "23MO0172",
    mgCode: "23MG0095",
    duration: "8",
  },
  {
    id: 442,
    title: "STRATEGIC PERFORMANCE MANAGEMENT",
    moCode: "23MO0173",
    mgCode: "23MG0096",
    duration: "8",
  },
  {
    id: 443,
    title: "BUSINESS FORECASTING",
    moCode: "23MO0174",
    mgCode: "23MG0097",
    duration: "8",
  },
  {
    id: 444,
    title: "BEHAVIORAL AND PERSONAL FINANCE",
    moCode: "23MO0175",
    mgCode: "23MG0098",
    duration: "8",
  },
  {
    id: 445,
    title: "PRINCIPLES OF INDUSTRIAL ENGINEERING",
    moCode: "23MO0183",
    mgCode: null,
    duration: "12",
  },
  {
    id: 446,
    title: "SUBSURFACE EXPLORATION :IMPORTANCE AND TECHNIQUES INVOLVED",
    moCode: "23MO0185",
    mgCode: null,
    duration: "8",
  },
  {
    id: 447,
    title: "INTRODUCTION TO CIVIL ENGINEERING PROFESSION",
    moCode: "23MO0186",
    mgCode: "24MG0034",
    duration: "8",
  },
  {
    id: 448,
    title: "ASPEN PLUS® SIMULATION SOFTWARE - A BASIC COURSE FOR BEGINNERS",
    moCode: "23MO0188",
    mgCode: null,
    duration: "12",
  },
  {
    id: 449,
    title:
      "MODERN FOOD PACKAGING TECHNOLOGIES: REGULATORY ASPECTS AND GLOBAL TRENDS",
    moCode: "23MO0189",
    mgCode: "24MG0035",
    duration: "12",
  },
  {
    id: 450,
    title: "INDUSTRIAL HYDRAULICS AND AUTOMATION",
    moCode: "23MO0190",
    mgCode: null,
    duration: "12",
  },
  {
    id: 451,
    title: "DISCRETE MATHEMATICS",
    moCode: "23MO0197",
    mgCode: null,
    duration: "12",
  },
  {
    id: 452,
    title:
      "BUSINESS FUNDAMENTALS FOR ENTREPRENEURS (PART 2: EXTERNAL OPERATION)",
    moCode: "23MO0204",
    mgCode: null,
    duration: "4",
  },
  {
    id: 453,
    title: "PATENT DRAFTING FOR BEGINNERS",
    moCode: "23MO0205",
    mgCode: null,
    duration: "4",
  },
  {
    id: 454,
    title: "UAV IN ENGINEERING APPLICATIONS",
    moCode: "23MO0206",
    mgCode: null,
    duration: "8",
  },
  {
    id: 455,
    title: "SOCIOLOGY AND SANITATION: AN INTRODUCTION",
    moCode: "24MO0001",
    mgCode: "24MG0036",
    duration: "4",
  },
  {
    id: 456,
    title: "COMBUSTION OF SOLID FUELS AND PROPELLANTS",
    moCode: "24MO0002",
    mgCode: "24MG0037",
    duration: "8",
  },
  {
    id: 457,
    title: "COMPUTER INTEGRATED MANUFACTURING",
    moCode: "24MO0003",
    mgCode: "24MG0038",
    duration: "12",
  },
  {
    id: 458,
    title: "CRYOGENIC HYDROGEN TECHNOLOGY",
    moCode: "24MO0004",
    mgCode: "24MG0039",
    duration: "8",
  },
  {
    id: 459,
    title: "ECONOMIC GROWTH AND DEVELOPMENT",
    moCode: "24MO0005",
    mgCode: "24MG0040",
    duration: "8",
  },
  {
    id: 460,
    title: "ENERGY RESOURCES, ECONOMICS, AND SUSTAINABILITY",
    moCode: "24MO0006",
    mgCode: "24MG0041",
    duration: "8",
  },
  {
    id: 461,
    title: "PSYCHOLOGY OF STRESS, HEALTH AND WELL-BEING",
    moCode: "24MO0007",
    mgCode: "24MG0042",
    duration: "12",
  },
  {
    id: 462,
    title: "BASICS OF HEALTH PROMOTION AND EDUCATION INTERVENTION",
    moCode: "24MO0008",
    mgCode: "24MG0043",
    duration: "8",
  },
  {
    id: 463,
    title: "INTRODUCTION TO COGNITIVE PSYCHOLOGY",
    moCode: "24MO0009",
    mgCode: "24MG0044",
    duration: "12",
  },
  {
    id: 464,
    title:
      "BIOMEDICAL ULTRASOUND: FUNDAMENTALS OF IMAGING AND MICROMACHINED TRANSDUCERS",
    moCode: "24MO0010",
    mgCode: "24MG0045",
    duration: "12",
  },
  {
    id: 465,
    title: "BASICS OF COMPUTATIONAL COMPLEXITY",
    moCode: "24MO0011",
    mgCode: "24MG0047",
    duration: "12",
  },
  {
    id: 466,
    title: "ADVANCED COMPUTER ARCHITECTURE",
    moCode: "24MO0012",
    mgCode: "24MG0048",
    duration: "12",
  },
  {
    id: 467,
    title: "PARALLEL COMPUTER ARCHITECTURE",
    moCode: "24MO0013",
    mgCode: "24MG0049",
    duration: "12",
  },
  {
    id: 468,
    title: "GAMES AND INFORMATION",
    moCode: "24MO0014",
    mgCode: "24MG0050",
    duration: "12",
  },
  {
    id: 469,
    title: "BUSINESS INTELLIGENCE & ANALYTICS",
    moCode: "24MO0015",
    mgCode: "24MG0051",
    duration: "12",
  },
  {
    id: 470,
    title: "PROBABILITY FOR COMPUTER SCIENCE",
    moCode: "24MO0016",
    mgCode: "24MG0052",
    duration: "8",
  },
  {
    id: 471,
    title: "OPTICAL WIRELESS COMMUNICATIONS FOR BEYOND 5G NETWORKS AND IOT",
    moCode: "24MO0017",
    mgCode: null,
    duration: "12",
  },
  {
    id: 472,
    title: "DIGITAL DESIGN WITH VERILOG",
    moCode: "24MO0018",
    mgCode: "24MG0053",
    duration: "12",
  },
  {
    id: 473,
    title: "COMPUTER NETWORKS AND INTERNET PROTOCOL",
    moCode: "24MO0019",
    mgCode: "24MG0054",
    duration: "12",
  },
  {
    id: 474,
    title:
      "COMPUTER VISION AND IMAGE PROCESSING - FUNDAMENTALS AND APPLICATIONS",
    moCode: "24MO0020",
    mgCode: "24MG0055",
    duration: "12",
  },
  {
    id: 475,
    title: "MANUFACTURING PROCESS TECHNOLOGY I & II",
    moCode: "24MO0021",
    mgCode: null,
    duration: "12",
  },
  {
    id: 476,
    title: "PRINCIPLES OF CASTING TECHNOLOGY",
    moCode: "24MO0022",
    mgCode: null,
    duration: "8",
  },
  {
    id: 477,
    title: "INTRODUCTION TO GRAPH ALGORITHMS",
    moCode: "24MO0023",
    mgCode: "24MG0063",
    duration: "8",
  },
  {
    id: 478,
    title: "ARTIFICIAL INTELLIGENCE FOR ECONOMICS",
    moCode: "24MO0024",
    mgCode: "24MG0064",
    duration: "8",
  },
  {
    id: 479,
    title: "DEEP LEARNING FOR COMPUTER VISION",
    moCode: "24MO0025",
    mgCode: "24MG0065",
    duration: "12",
  },
  {
    id: 480,
    title: "SUSTAINABLE ENERGY TECHNOLOGY",
    moCode: "24MO0026",
    mgCode: "24MG0122",
    duration: "12",
  },
  {
    id: 481,
    title: "TECHNICAL COMMUNICATION FOR ENGINEERS",
    moCode: "24MO0027",
    mgCode: null,
    duration: "4",
  },
  {
    id: 482,
    title: "WELDING APPLICATION TECHNOLOGY",
    moCode: null,
    mgCode: "24MG0070",
    duration: "8",
  },
  {
    id: 483,
    title: "DISTRIBUTED OPTIMIZATION AND MACHINE LEARNING",
    moCode: "24MO0028",
    mgCode: "24MG0071",
    duration: "12",
  },
  {
    id: 484,
    title: "RESPONSIBLE & SAFE AI SYSTEMS",
    moCode: "24MO0029",
    mgCode: "24MG0073",
    duration: "12",
  },
  {
    id: 485,
    title:
      "ELECTRONIC SYSTEMS DESIGN: HANDS-ON CIRCUITS AND PCB DESIGN WITH CAD SOFTWARE",
    moCode: "24MO0030",
    mgCode: "24MG0075",
    duration: "12",
  },
  {
    id: 486,
    title: "PROGRAMMING IN PYTHON",
    moCode: "24MO0031",
    mgCode: "24MG0076",
    duration: "12",
  },
  {
    id: 487,
    title: "IMMUNOLOGY",
    moCode: "24MO0032",
    mgCode: "24MG0077",
    duration: "12",
  },
  {
    id: 488,
    title: "SUSTAINABLE HAPPINESS",
    moCode: "24MO0033",
    mgCode: "24MG0080",
    duration: "8",
  },
  {
    id: 489,
    title: "MANAGEMENT OF MEDICAL EMERGENCIES IN DENTAL PRACTICE",
    moCode: "24MO0034",
    mgCode: "24MG0082",
    duration: "8",
  },
  {
    id: 490,
    title: "MODERN CONSTRUCTION MATERIALS",
    moCode: "24MO0035",
    mgCode: "24MG0085",
    duration: "12",
  },
  {
    id: 491,
    title: "BUSINESS DEVELOPMENT: FROM START TO SCALE",
    moCode: "24MO0036",
    mgCode: "24MG0087",
    duration: "12",
  },
  {
    id: 492,
    title: "AI IN MARKETING",
    moCode: "24MO0037",
    mgCode: "24MG0088",
    duration: "12",
  },
  {
    id: 493,
    title: "FUNDAMENTALS OF COST ACCOUNTING",
    moCode: "24MO0038",
    mgCode: "24MG0089",
    duration: "8",
  },
  {
    id: 494,
    title: "PRACTICAL CYBER SECURITY FOR CYBER SECURITY PRACTITIONERS",
    moCode: "24MO0039",
    mgCode: "24MG0095",
    duration: "12",
  },
  {
    id: 495,
    title: "COMPUTATIONAL ARITHMETIC - GEOMETRY FOR ALGEBRAIC CURVES",
    moCode: "24MO0040",
    mgCode: "24MG0096",
    duration: "12",
  },
  {
    id: 496,
    title: "SOCIAL NETWORK ANALYSIS",
    moCode: "24MO0041",
    mgCode: "24MG0097",
    duration: "12",
  },
  {
    id: 497,
    title: "APPROXIMATION ALGORITHM",
    moCode: "24MO0042",
    mgCode: "24MG0098",
    duration: "12",
  },
  {
    id: 498,
    title: "VLSI DESIGN FLOW: RTL TO GDS",
    moCode: "24MO0043",
    mgCode: "24MG0099",
    duration: "12",
  },
  {
    id: 499,
    title: "PRINCIPLES OF MODERN CDMA/ MIMO/ OFDM WIRELESS COMMUNICATIONS",
    moCode: "24MO0044",
    mgCode: "24MG0100",
    duration: "8",
  },
  {
    id: 500,
    title: "MODERN DIGITAL COMMUNICATION TECHNIQUES",
    moCode: "24MO0045",
    mgCode: "24MG0101",
    duration: "12",
  },
  {
    id: 501,
    title:
      "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING IN MATERIALS ENGINEERING",
    moCode: "24MO0046",
    mgCode: "24MG0102",
    duration: "12",
  },
  {
    id: 502,
    title: "NATURE AND PROPERTIES OF MATERIALS-AN INTRODUCTORY COURSE",
    moCode: "24MO0047",
    mgCode: "24MG0103",
    duration: "8",
  },
  {
    id: 503,
    title: "INTRODUCTION TO LANGUAGE AND LINGUISTICS",
    moCode: "24MO0048",
    mgCode: "24MG0104",
    duration: "12",
  },
  {
    id: 504,
    title: "KOREAN I",
    moCode: "24MO0049",
    mgCode: "24MG0105",
    duration: "12",
  },
  {
    id: 505,
    title: "INTRODUCTION TO BIOMIMICRY",
    moCode: "24MO0050",
    mgCode: "24MG0114",
    duration: "8",
  },
  {
    id: 506,
    title: "COGNITION AND ITS COMPUTATION",
    moCode: "24MO0051",
    mgCode: "24MG0115",
    duration: "12",
  },
  {
    id: 507,
    title: "AN INTRODUCTION TO CLIMATE DYNAMICS, VARIABILITY AND MONITORING",
    moCode: "24MO0052",
    mgCode: null,
    duration: "12",
  },
  {
    id: 508,
    title: "ANIMATIONS",
    moCode: "24MO0053",
    mgCode: null,
    duration: "15",
  },
  {
    id: 509,
    title: "CONSERVATION GEOGRAPHY",
    moCode: "24MO0054",
    mgCode: null,
    duration: "12",
  },
  {
    id: 510,
    title: "EDUCATIONAL LEADERSHIP",
    moCode: "24MO0055",
    mgCode: null,
    duration: "8",
  },
  {
    id: 511,
    title: "ETHICS IN ENGINEERING PRACTICE",
    moCode: "24MO0056",
    mgCode: null,
    duration: "8",
  },
  {
    id: 512,
    title: "HYDROGEN ENERGY: PRODUCTION, STORAGE, TRANSPORTATION AND SAFETY",
    moCode: "24MO0057",
    mgCode: null,
    duration: "12",
  },
  {
    id: 513,
    title:
      "INTRODUCTION TO BASIC SPOKEN SANSKRIT AND INTERMEDIATE LEVEL OF SPOKEN SANSKRIT",
    moCode: "24MO0058",
    mgCode: null,
    duration: "12",
  },
  {
    id: 514,
    title:
      "INTRODUCTION TO ENVIRONMENTAL ENGINEERING AND SCIENCE - FUNDAMENTAL AND SUSTAINABILITY CONCEPTS",
    moCode: "24MO0059",
    mgCode: null,
    duration: "12",
  },
  {
    id: 515,
    title: "INTRODUCTION TO EXERCISE PHYSIOLOGY & SPORTS PERFORMANCE",
    moCode: "24MO0060",
    mgCode: null,
    duration: "8",
  },
  {
    id: 516,
    title: "INTRODUCTION TO URBAN PLANNING",
    moCode: "24MO0061",
    mgCode: null,
    duration: "8",
  },
  {
    id: 517,
    title: "MATERIALS PROCESSING (CASTING, FORMING AND WELDING)",
    moCode: "24MO0062",
    mgCode: null,
    duration: "12",
  },
  {
    id: 518,
    title: "METALLURGICAL AND ELECTRONIC WASTE RECYCLING",
    moCode: "24MO0063",
    mgCode: null,
    duration: "8",
  },
  {
    id: 519,
    title: "PERSONALITY DEVELOPMENT",
    moCode: "24MO0064",
    mgCode: null,
    duration: "8",
  },
  {
    id: 520,
    title: "PHYSICS OF RENEWABLE ENERGY SYSTEMS",
    moCode: "24MO0065",
    mgCode: null,
    duration: "12",
  },
  {
    id: 521,
    title: "PRINCIPLES OF METAL FORMING TECHNOLOGY",
    moCode: "24MO0066",
    mgCode: null,
    duration: "8",
  },
  {
    id: 522,
    title: "REMOTE SENSING AND GIS",
    moCode: "24MO0067",
    mgCode: null,
    duration: "8",
  },
  {
    id: 523,
    title: "RESEARCH ETHICS AND PLAGIARISM",
    moCode: "24MO0068",
    mgCode: null,
    duration: "8",
  },
  {
    id: 524,
    title: "UNDERSTANDING DISCIPLINES AND SUBJECTS",
    moCode: "24MO0069",
    mgCode: null,
    duration: "8",
  },
  {
    id: 525,
    title: "BUSINESS AND SUSTAINABLE DEVELOPMENT",
    moCode: "24MO0070",
    mgCode: null,
    duration: "4",
  },
  {
    id: 526,
    title:
      "BUSINESS FUNDAMENTALS FOR ENTREPRENEURS (PART 1: INTERNAL OPERATION)",
    moCode: "24MO0071",
    mgCode: null,
    duration: "4",
  },
  {
    id: 527,
    title: "CMOS DIGITAL VLSI DESIGN",
    moCode: "24MO0072",
    mgCode: "24MG0128",
    duration: "8",
  },
  {
    id: 528,
    title: "INDIAN POETRY IN ENGLISH",
    moCode: "24MO0073",
    mgCode: null,
    duration: "8",
  },
  {
    id: 529,
    title: "MICROBIAL BIOTECHNOLOGY",
    moCode: null,
    mgCode: "24MG0130",
    duration: "12",
  },
];
