export const courses = [
  {
    id: 1,
    title: "AIRCRAFT MAINTENANCE",
    moCode: "21MO0004",
    mgCode: null,
    duration: "4",
    dept: "AERO",
  },
  {
    id: 2,
    title: "AN INTERFACE WITH BIOLOGY AND MEDICINE",
    moCode: "21MO0006",
    mgCode: null,
    duration: "8",
    dept: "BME",
  },
  {
    id: 3,
    title: "APPLIED NATURAL PROCESSING",
    moCode: "21MO0015",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 4,
    title: "BIOREACTOR DESIGN AND ANALYSIS",
    moCode: "21MO0042",
    mgCode: "24MG0057",
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 5,
    title: "BRIEF INTRODUCTION TO PSYCHOLOGY",
    moCode: "21MO0048",
    mgCode: null,
    duration: "4",
    dept: "CRIMINOLOGY",
  },
  {
    id: 6,
    title: "Cell Culture Technologies",
    moCode: "21MO0057",
    mgCode: "24MG0119",
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 7,
    title: "CLASSICAL SOCIOLOGICAL THEORY",
    moCode: "21MO0060",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 8,
    title: "CLOUD COMPUTING AND DISTRIBUTED SYSTEMS",
    moCode: "21MO0061",
    mgCode: "23MG0030",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 9,
    title: "COMMUNICATION SKILLS",
    moCode: "21MO0064",
    mgCode: null,
    duration: "12",
    dept: "COMMERCE",
  },
  {
    id: 10,
    title: "COMPUTER APPLICATION IN BUSINESS",
    moCode: "21MO0066",
    mgCode: null,
    duration: "12",
    dept: "COMMERCE",
  },
  {
    id: 11,
    title:
      "CONSTITUTION OF INDIA AND ENVIRONMENTAL GOVERNANCE: ADMINISTRATIVE AND ADJUDICATORY PROCESS",
    moCode: "21MO0069",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 12,
    title:
      "Current regulatory requirements for conducting clinical trials in India for investigational new drugs/new drug (Version 3.0)",
    moCode: "21MO0078",
    mgCode: "24MG0121",
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 13,
    title: "DEMYSTIFYING THE BRAIN",
    moCode: "21MO0097",
    mgCode: null,
    duration: "4",
    dept: "BIOTECH",
  },
  {
    id: 14,
    title: "DESCRIPTIVE STATISTICS WITH R SOFTWARE",
    moCode: "21MO0098",
    mgCode: null,
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 15,
    title: "DESIGN THINKING - A PRIMER",
    moCode: "21MO0101",
    mgCode: null,
    duration: "4",
    dept: "AERO",
  },
  {
    id: 16,
    title: "DEVELOPING SOFT SKILLS AND PERSONALITY",
    moCode: "21MO0106",
    mgCode: "23MG0013",
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 17,
    title: "DEVELOPMENT RESEARCH METHODS",
    moCode: "21MO0108",
    mgCode: null,
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 18,
    title: "EARTH SCIENCES FOR CIVIL ENGINEERING PART - I & II",
    moCode: "21MO0115",
    mgCode: null,
    duration: "8",
    dept: "CIVIL",
  },
  {
    id: 19,
    title: "Emotional Intelligence",
    moCode: "21MO0121",
    mgCode: "24MG0001",
    duration: "12",
    dept: "MBA",
  },
  {
    id: 20,
    title: "ENGLISH LANGUAGE FOR COMPETITIVE EXAMS",
    moCode: "21MO0123",
    mgCode: "23MG0078",
    duration: "12",
    dept: "BME",
  },
  {
    id: 21,
    title: "FINANCIAL INSTITUTIONS AND MARKETS",
    moCode: "21MO0134",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 22,
    title: "FOOD NUTRITION FOR HEALTHY LIVING",
    moCode: "21MO0139",
    mgCode: null,
    duration: "24",
    dept: "FOOD",
  },
  {
    id: 23,
    title: "Forests and their Management",
    moCode: "21MO0140",
    mgCode: "24MG0046",
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 24,
    title: "FOUNDATION COURSE IN MANAGERIAL ECONOMICS",
    moCode: "21MO0141",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 25,
    title: "FUZZY SETS, LOGIC AND SYSTEMS & APPLICATIONS",
    moCode: "21MO0151",
    mgCode: null,
    duration: "12",
    dept: "EEE",
  },
  {
    id: 26,
    title: "GENDER JUSTICE AND WORKPLACE SECURITY",
    moCode: "21MO0152",
    mgCode: null,
    duration: "4",
    dept: "CRIMINOLOGY",
  },
  {
    id: 27,
    title: "German-I",
    moCode: "21MO0156",
    mgCode: "24MG0002",
    duration: "12",
    dept: "MECH",
  },
  {
    id: 28,
    title: "Great experiments in psychology",
    moCode: "21MO0167",
    mgCode: "24MG0003",
    duration: "4",
    dept: "CRIMINOLOGY",
  },
  {
    id: 29,
    title: "HUMAN BEHAVIOUR",
    moCode: "21MO0175",
    mgCode: "23MG0085",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 30,
    title: "HUMAN MOLECULAR GENETICS",
    moCode: "21MO0176",
    mgCode: null,
    duration: "4",
    dept: "BIOTECH",
  },
  {
    id: 31,
    title: "HUMAN RESOURCE DEVELOPMENT",
    moCode: "21MO0178",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 32,
    title: "HUMAN RIGHTS LAW AND CRIMINAL JUSTICE",
    moCode: "21MO0179",
    mgCode: null,
    duration: "12",
    dept: "CHEMISTRY",
  },
  {
    id: 33,
    title: "INTRODUCTION TO DEVELOPMENT BIOLOGY",
    moCode: "21MO0218",
    mgCode: null,
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 34,
    title: "Introduction to Experiments in Flight",
    moCode: "21MO0220",
    mgCode: "24MG0004",
    duration: "4",
    dept: "AERO",
  },
  {
    id: 35,
    title: "INTRODUCTION TO INDUSTRY 4.0 AND INDUSTRIAL INTERNET OF THINGS",
    moCode: "21MO0227",
    mgCode: "23MG0031",
    duration: "12",
    dept: "RE",
  },
  {
    id: 36,
    title: "INTRODUCTION TO INTERNET OF THINGS",
    moCode: "21MO0229",
    mgCode: "23MG0007",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 37,
    title: "INTRODUCTION TO LAW ON ELECTRICITY",
    moCode: "21MO0232",
    mgCode: null,
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 38,
    title: "INTRODUCTION TO R SOFTWARE",
    moCode: "21MO0239",
    mgCode: null,
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 39,
    title: "INTRODUCTION TO RESEARCH",
    moCode: "21MO0240",
    mgCode: null,
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 40,
    title: "Introductory Mathematical Methods for Biologists",
    moCode: "21MO0249",
    mgCode: "24MG0111",
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 41,
    title: "LEGAL AND REGULATORY ISSUES IN BIOTECHNOLOGY",
    moCode: "21MO0257",
    mgCode: null,
    duration: "4",
    dept: "CRIMINOLOGY",
  },
  {
    id: 42,
    title: "MACHINING SCIENCE",
    moCode: "21MO0265",
    mgCode: null,
    duration: "4",
    dept: "MECH",
  },
  {
    id: 43,
    title: "ORGANIZATION THEORY / STRUCTURE AND DESIGN",
    moCode: "21MO0283",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 44,
    title: "ORGANIZATIONAL BEHAVIOUR I",
    moCode: "21MO0284",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 45,
    title: "ORGANIZATIONAL BEHAVIOUR II",
    moCode: "21MO0285",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 46,
    title: "PATENT LAW FOR ENGINEERS AND SCIENTISTS",
    moCode: "21MO0288",
    mgCode: null,
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 47,
    title: "PRINCIPLES OF GENETICS",
    moCode: "21MO0297",
    mgCode: null,
    duration: "12",
    dept: "CHEMISTRY",
  },
  {
    id: 48,
    title: "PRINCIPLES OF HUMAN RESOURCE MANAGEMENT",
    moCode: "21MO0298",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 49,
    title: "PROBABILITY AND STATISTICS",
    moCode: "21MO0301",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 50,
    title: "PROJECT ANALYSIS",
    moCode: "21MO0308",
    mgCode: null,
    duration: "12",
    dept: "COMMERCE",
  },
  {
    id: 51,
    title: "PROPERTIES OF MATERIAL(NATURE AND PROPERTIES OF MATERIAL:III)",
    moCode: "21MO0310",
    mgCode: null,
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 52,
    title: "PYTHON FOR DATA SCIENCE",
    moCode: "21MO0315",
    mgCode: "23MG0032",
    duration: "4",
    dept: "BME",
  },
  {
    id: 53,
    title: "REGRESSION ANALYSIS",
    moCode: "21MO0320",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 54,
    title: "Reinforcement Learning",
    moCode: "21MO0321",
    mgCode: "24MG0005",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 55,
    title: "RIGHT TO INFORMATION AND GOOD GOVERNANCE",
    moCode: "21MO0324",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 56,
    title: "SCHEDULING TECHINQUES IN PROJECTS",
    moCode: "21MO0326",
    mgCode: null,
    duration: "4",
    dept: "CIVIL",
  },
  {
    id: 57,
    title: "SENSORS AND ACTUATORS",
    moCode: "21MO0328",
    mgCode: null,
    duration: "12",
    dept: "BME",
  },
  {
    id: 58,
    title: "SMART MATERIALS AND INTELLIGENT SYSTEM DESIGN",
    moCode: "21MO0335",
    mgCode: null,
    duration: "4",
    dept: "FOOD",
  },
  {
    id: 59,
    title: "SOCIAL NETWORKS",
    moCode: "21MO0336",
    mgCode: "23MG0033",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 60,
    title: "SOCIOLOGY OF DEVELOPMENT",
    moCode: "21MO0339",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 61,
    title: "SOFT NANOTECHNOLOGY",
    moCode: "21MO0340",
    mgCode: null,
    duration: "8",
    dept: "PHY",
  },
  {
    id: 62,
    title: "SOFTWARE TESTING",
    moCode: "21MO0341",
    mgCode: "23MG0034",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 63,
    title: "STRESS MANAGEMENT",
    moCode: "21MO0347",
    mgCode: null,
    duration: "4",
    dept: "CRIMINOLOGY",
  },
  {
    id: 64,
    title: "STRUCTURAL BIOLOGY",
    moCode: "21MO0349",
    mgCode: "24MG0058",
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 65,
    title: "DATA MINING",
    moCode: "21MO0412",
    mgCode: "23MG0035",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 66,
    title: "ADVANCED MACHINING PROCESSES",
    moCode: "21MO0414",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 67,
    title: "HUMAN RIGHTS, LAW AND CRIMINAL JUSTICE",
    moCode: "21MO0417",
    mgCode: null,
    duration: "12",
    dept: "CRIMINOLOGY",
  },
  {
    id: 68,
    title: "ADVANCED GRAPH THEORY",
    moCode: "21MO0431",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 69,
    title: "AIRCRAFT DESIGN",
    moCode: "21MO0432",
    mgCode: null,
    duration: "12",
    dept: "AERO",
  },
  {
    id: 70,
    title: "AIRCRAFT PROPULSION",
    moCode: "21MO0433",
    mgCode: null,
    duration: "12",
    dept: "MECH",
  },
  {
    id: 71,
    title: "AN INTRODUCTION TO ARTIFICIAL INTELLIGENCE",
    moCode: "21MO0435",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 72,
    title: "BIG DATA COMPUTING",
    moCode: "21MO0447",
    mgCode: "23MG0036",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 73,
    title: "BIOLOGICAL INORGANIC CHEMISTRY",
    moCode: "21MO0448",
    mgCode: null,
    duration: "12",
    dept: "CHEMISTRY",
  },
  {
    id: 74,
    title: "Blockchain and its Applications",
    moCode: "21MO0450",
    mgCode: "24MG0006",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 75,
    title: "CLOUD COMPUTING",
    moCode: "21MO0459",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 76,
    title: "COGNITION, TRANSFORMATION, AND LIVES",
    moCode: "21MO0460",
    mgCode: null,
    duration: "4",
    dept: "CHEMISTRY",
  },
  {
    id: 77,
    title: "DAIRY AND FOOD PROCESS AND PRODUCTS TECHNOLOGY",
    moCode: "21MO0466",
    mgCode: "23MG0073",
    duration: "12",
    dept: "FOOD",
  },
  {
    id: 78,
    title: "Data Analytics with Python",
    moCode: "21MO0467",
    mgCode: "24MG0007",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 79,
    title: "DEEP LEARNING",
    moCode: "21MO0471",
    mgCode: "24MG0090",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 80,
    title: "DIGITAL CIRCUITS",
    moCode: "21MO0473",
    mgCode: "23MG0002",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 81,
    title: "ELEMENTS OF LITERATURE AND CREATIVE COMMUNICATION",
    moCode: "21MO0476",
    mgCode: null,
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 82,
    title: "EMBEDDED SYSTEMS DESIGN",
    moCode: "21MO0477",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 83,
    title: "ENGLISH LITERATURE OF THE ROMANTIC PERIOD, 1798-1832",
    moCode: "21MO0482",
    mgCode: null,
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 84,
    title: "ENVIRONMENTAL IMPACT ASSESSMENT",
    moCode: "21MO0483",
    mgCode: null,
    duration: "12",
    dept: "CIVIL",
  },
  {
    id: 85,
    title: "ENVIRONMENTAL REMEDIATION AND CONTAMINATED SITES",
    moCode: "21MO0484",
    mgCode: null,
    duration: "12",
    dept: "CIVIL",
  },
  {
    id: 86,
    title: "ETHICAL HACKING",
    moCode: "21MO0486",
    mgCode: "24MG0072",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 87,
    title: "FOOD AND NUTRITION",
    moCode: "21MO0487",
    mgCode: null,
    duration: "12",
    dept: "FOOD",
  },
  {
    id: 88,
    title: "FOOD LAWS AND STANDARDS",
    moCode: "21MO0488",
    mgCode: null,
    duration: "16",
    dept: "FOOD",
  },
  {
    id: 89,
    title: "FOOD MICROBIOLOGY AND FOOD SAFETY",
    moCode: "21MO0489",
    mgCode: null,
    duration: "15",
    dept: "FOOD",
  },
  {
    id: 90,
    title: "FUNCTIONAL FOODS AND NEUTRACEUTICALS",
    moCode: "21MO0491",
    mgCode: null,
    duration: "15",
    dept: "FOOD",
  },
  {
    id: 91,
    title: "FUNDAMENTALS OF ARTIFICIAL INTELLIGENCE",
    moCode: "21MO0492",
    mgCode: "24MG0081",
    duration: "12",
    dept: "MECH",
  },
  {
    id: 92,
    title: "FUNDAMENTALS OF AUTOMOTIVE SYSTEMS",
    moCode: "21MO0493",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 93,
    title: "FUNDAMENTALS OF COMPUTER SYSTEM",
    moCode: "21MO0494",
    mgCode: null,
    duration: "12",
    dept: "DS",
  },
  {
    id: 94,
    title: "German-II",
    moCode: "21MO0501",
    mgCode: "24MG0008",
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 95,
    title: "Getting Started with Competitive Programming",
    moCode: "21MO0502",
    mgCode: "24MG0009",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 96,
    title: "GPU Architectures And Programming",
    moCode: "21MO0505",
    mgCode: "24MG0010",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 97,
    title: "HISTORY OF ENGLISH LANGUAGE AND LITERATURE",
    moCode: "21MO0506",
    mgCode: "24MG0074",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 98,
    title: "INFORMATION SECURITY - 5 - SECURE SYSTEMS ENGINEERING",
    moCode: "21MO0509",
    mgCode: "23MG0037",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 99,
    title: "INSTRUMENTATION AND PROCESS CONTROL IN FOOD INDUSTRY",
    moCode: "21MO0510",
    mgCode: null,
    duration: "8",
    dept: "FOOD",
  },
  {
    id: 100,
    title: "INTRODUCTION TO ALGORITHMS AND ANALYSIS",
    moCode: "21MO0511",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 101,
    title: "INTRODUCTION TO BASIC COGNITIVE PROCESSES",
    moCode: "21MO0513",
    mgCode: "23MG0014",
    duration: "8",
    dept: "CHEMISTRY",
  },
  {
    id: 102,
    title: "INTRODUCTION TO JAPANESE LANGUAGE AND CULTURE",
    moCode: "21MO0518",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 103,
    title: "INTRODUCTION TO LAUNCH VEHICLE ANALYSIS AND DESIGN",
    moCode: "21MO0519",
    mgCode: null,
    duration: "8",
    dept: "AERO",
  },
  {
    id: 104,
    title: "INTRODUCTION TO PSYCHOLOGY",
    moCode: "21MO0525",
    mgCode: "23MG0015",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 105,
    title: "Introduction to Semiconductor Devices",
    moCode: "21MO0526",
    mgCode: "24MG0106",
    duration: "12",
    dept: "AERO",
  },
  {
    id: 106,
    title: "INTRODUCTION TO WORLD LITERATURE",
    moCode: "21MO0529",
    mgCode: null,
    duration: "12",
    dept: "BIOTECH",
  },
  {
    id: 107,
    title: "MEDICAL BIOMATERIALS",
    moCode: "21MO0534",
    mgCode: "24MG0059",
    duration: "8",
    dept: "PHYSICS",
  },
  {
    id: 108,
    title: "MULTI-CORE COMPUTER ARCHITECTURE - STORAGE AND INTERCONNECTS",
    moCode: "21MO0535",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 109,
    title: "NANOTECHNOLOGY IN AGRICULTURE",
    moCode: "21MO0536",
    mgCode: "23MG0011",
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 110,
    title: "NUCLEAR ASTROPHYSICS",
    moCode: "21MO0539",
    mgCode: null,
    duration: "8",
    dept: "PHYSICS",
  },
  {
    id: 111,
    title: "ONLINE PRIVACY",
    moCode: "21MO0540",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 112,
    title: "PROGRAMMING IN MODERN C++",
    moCode: "21MO0547",
    mgCode: "23MG0038",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 113,
    title: "Programming, Data Structures and Algorithms using Python",
    moCode: "21MO0549",
    mgCode: "24MG0107",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 114,
    title: "RURAL WATER RESOURCES MANAGEMENT",
    moCode: "21MO0553",
    mgCode: null,
    duration: "12",
    dept: "CIVIL",
  },
  {
    id: 115,
    title: "SAFETY IN CONSTRUCTION",
    moCode: "21MO0554",
    mgCode: null,
    duration: "8",
    dept: "CIVIL",
  },
  {
    id: 116,
    title: "SEMICONDUCTOR DEVICES AND CIRCUITS",
    moCode: "21MO0556",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 117,
    title: "SOFTWARE TESTING",
    moCode: "21MO0559",
    mgCode: null,
    duration: "4",
    dept: "CSE",
  },
  {
    id: 118,
    title: "SPEAKING EFFECTIVELY",
    moCode: "21MO0561",
    mgCode: "23MG0039",
    duration: "8",
    dept: "BIOTECH",
  },
  {
    id: 119,
    title:
      "SPECTROSCOPIC TECHNIQUES FOR PHARMACEUTICAL AND BIOPHARMACEUTICAL COMPANIES",
    moCode: "21MO0562",
    mgCode: null,
    duration: "12",
    dept: "CHEMISTRY",
  },
  {
    id: 120,
    title: "TECHNICAL ENGLISH FOR ENGINEERS",
    moCode: "21MO0565",
    mgCode: "23MG0068",
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 121,
    title: "THE JOY OF COMPUTING USING PYTHON",
    moCode: "21MO0568",
    mgCode: "23MG0079",
    duration: "12",
    dept: "AERO",
  },
  {
    id: 122,
    title: "THERMAL PROCESSING OF FOODS",
    moCode: "21MO0570",
    mgCode: null,
    duration: "12",
    dept: "FOOD",
  },
  {
    id: 123,
    title: "VLSI PHYSICAL DESIGN",
    moCode: "21MO0575",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 124,
    title: "WORK SYSTEM DESIGN",
    moCode: "21MO0577",
    mgCode: null,
    duration: "12",
    dept: "MECH",
  },
  {
    id: 125,
    title: "ADVANCED COMPUTER ARCHITECTURE",
    moCode: "22MO0002",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 126,
    title: "ANIMAL PHYSIOLOGY",
    moCode: "22MO0005",
    mgCode: "23MG0009",
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 127,
    title: "APPLIED ERGONOMICS",
    moCode: "22MO0006",
    mgCode: null,
    duration: "12",
    dept: "MECH",
  },
  {
    id: 128,
    title: "Biomedical nanotechnology",
    moCode: "22MO0007",
    mgCode: "24MG0011",
    duration: "4",
    dept: "Biotech",
  },
  {
    id: 129,
    title: "BIOREACTORS",
    moCode: "22MO0008",
    mgCode: null,
    duration: "4",
    dept: "Biotech",
  },
  {
    id: 130,
    title: "COMPUTATIONAL GEOMETRY",
    moCode: "22MO0011",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 131,
    title: "COMPUTER AIDED DRUG DESIGN",
    moCode: "22MO0012",
    mgCode: null,
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 132,
    title: "DESIGN AND ENGINEERING OF COMPUTER SYSTEMS",
    moCode: "22MO0013",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 133,
    title: "DESIGN PRACTICE",
    moCode: "22MO0014",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 134,
    title: "ENVIRONMENTAL BIOTECHNOLOGY",
    moCode: "22MO0015",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 135,
    title: "EXPLOSIONS AND SAFETY",
    moCode: "22MO0017",
    mgCode: null,
    duration: "12",
    dept: "MECH",
  },
  {
    id: 136,
    title: "FUNDAMENTAL OF WELDING SCIENCE AND TECHNOLOGY",
    moCode: "22MO0018",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 137,
    title: "HARDWARE SECURITY",
    moCode: "22MO0021",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 138,
    title: "INDUSTRIAL BIOTECHNOLOGY",
    moCode: "22MO0023",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 139,
    title: "INNOVATION, BUSINESS MODELS AND ENTREPRENEURSHIP",
    moCode: "22MO0024",
    mgCode: "23MG0008",
    duration: "8",
    dept: "BME",
  },
  {
    id: 140,
    title: "INTRODUCTION TO ABRASIVE MACHINING AND FINISHING PROCESSES",
    moCode: "22MO0026",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 141,
    title: "INTRODUCTION TO BIOSTATISTICS",
    moCode: "22MO0027",
    mgCode: null,
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 142,
    title: "INTRODUCTION TO DEVELOPMENTAL BIOLOGY",
    moCode: "22MO0028",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 143,
    title: "INTRODUCTION TO MACHINING AND MACHINING FLUIDS",
    moCode: "22MO0030",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 144,
    title: "INTRODUCTION TO PARALLEL PROGRAMMING WITH OPENMP AND MPI",
    moCode: "22MO0031",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 145,
    title: "INTRODUCTION TO UNCERTAINTY ANALYSIS AND EXPERIMENTATION",
    moCode: "22MO0034",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 146,
    title: "MANUFACTURING AUTOMATION",
    moCode: "22MO0035",
    mgCode: "23MG0091",
    duration: "4",
    dept: "MECH",
  },
  {
    id: 147,
    title: "MECHANICAL MEASUREMENT SYSTEM",
    moCode: "22MO0036",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 148,
    title: "MECHANICS OF MACHINING",
    moCode: "22MO0037",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 149,
    title: "MODEL CHECKING",
    moCode: "22MO0039",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 150,
    title: "NATURE AND PROPERTIES OF MATERIALS",
    moCode: "22MO0040",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 151,
    title: "Plant Cell Bioprocessing",
    moCode: "22MO0042",
    mgCode: "24MG0112",
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 152,
    title: "PROGRAMMING IN JAVA",
    moCode: "22MO0044",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 153,
    title: "ROBOTICS AND CONTROL : THEORY AND PRACTICE",
    moCode: "22MO0045",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 154,
    title: "SOFT SKILLS",
    moCode: "22MO0046",
    mgCode: "23MG0074",
    duration: "12",
    dept: "PHYSICS",
  },
  {
    id: 155,
    title: "SOFT SKILLS FOR BUSINESS NEGOTIATIONS AND MARKETING STRATEGIES",
    moCode: "22MO0047",
    mgCode: null,
    duration: "12",
    dept: "PHYSICS",
  },
  {
    id: 156,
    title: "SOFTWARE CONCEPTUAL DESIGN",
    moCode: "22MO0048",
    mgCode: "23MG0040",
    duration: "4",
    dept: "CSE",
  },
  {
    id: 157,
    title: "STEAM AND GAS POWER SYSTEMS",
    moCode: "22MO0049",
    mgCode: null,
    duration: "8",
    dept: "MECH",
  },
  {
    id: 158,
    title: "SYSTEMS AND USABLE SECURITY",
    moCode: "22MO0050",
    mgCode: "23MG0041",
    duration: "4",
    dept: "CSE",
  },
  {
    id: 159,
    title: "TISSUE ENGINEERING",
    moCode: "22MO0051",
    mgCode: null,
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 160,
    title: "POLLUTANTS AND WATER SUPPLY",
    moCode: "22MO0053",
    mgCode: null,
    duration: "16",
    dept: "CIVIL",
  },
  {
    id: 161,
    title: "INTRODUCTION TO SOFT COMPUTING",
    moCode: "22MO0057",
    mgCode: "23MG0042",
    duration: "8",
    dept: "ROBO",
  },
  {
    id: 162,
    title: "LITERATURE FOR COMPETITIVE EXAMS",
    moCode: "22MO0059",
    mgCode: null,
    duration: "8",
    dept: "FOOD",
  },
  {
    id: 163,
    title: "NOVEL TECHNOLOGIES FOR FOOD PROCESSING AND SHELF LIFE EXTENSION",
    moCode: "22MO0060",
    mgCode: "24MG0069",
    duration: "12",
    dept: "FOOD",
  },
  {
    id: 164,
    title: "NANOTECHNOLOGY, SCIENCE AND APPLICATIONS",
    moCode: "22MO0062",
    mgCode: null,
    duration: "8",
    dept: "NANO",
  },
  {
    id: 165,
    title: "A brief introduction of Micro - Sensors",
    moCode: "22MO0063",
    mgCode: null,
    duration: "4",
    dept: "Aero",
  },
  {
    id: 166,
    title: "Advanced Computer Networks",
    moCode: "22MO0064",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 167,
    title: "Advanced Distributed systems",
    moCode: "22MO0065",
    mgCode: "23MG0043",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 168,
    title: "Advanced Neural Science for Engineers",
    moCode: "22MO0066",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 169,
    title: "Affective Computing",
    moCode: "22MO0067",
    mgCode: "24MG0012",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 170,
    title: "AI:Constraint Satisfaction",
    moCode: "22MO0068",
    mgCode: "23MG0044",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 171,
    title: "Algorithmic Game Theory",
    moCode: "22MO0069",
    mgCode: "24MG0091",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 172,
    title: "Analog Electronic Circuits",
    moCode: "22MO0070",
    mgCode: null,
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 173,
    title: "Analysis and Design Principles of Microwave Antennas",
    moCode: "22MO0071",
    mgCode: null,
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 174,
    title: "Applied Accelerated Artificial Intelligence",
    moCode: "22MO0073",
    mgCode: "23MG0045",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 175,
    title: "Applied Linear Algebra in AI and ML",
    moCode: "22MO0074",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 176,
    title: "Artificial Intelligence Search Methods For Problem Solving",
    moCode: "22MO0075",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 177,
    title: "Artificial Intelligence: Knowledge Representation And Reasoning",
    moCode: "22MO0076",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 178,
    title: "Automation in Manufacturing",
    moCode: "22MO0077",
    mgCode: "24MG0116",
    duration: "12",
    dept: "Mech",
  },
  {
    id: 179,
    title: "Basic Construction materials",
    moCode: "22MO0078",
    mgCode: null,
    duration: "12",
    dept: "Civil",
  },
  {
    id: 180,
    title: "Basics of Biology",
    moCode: "22MO0079",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 181,
    title: "Bioengineering: An Interface with Biology and Medicine",
    moCode: "22MO0080",
    mgCode: null,
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 182,
    title: "Biointerface Engineering",
    moCode: "22MO0081",
    mgCode: "24MG0083",
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 183,
    title: "Biomechanics",
    moCode: "22MO0082",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 184,
    title: "C-Based VLSI Design",
    moCode: "22MO0083",
    mgCode: "23MG0046",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 185,
    title: "Circuit Complexity Theory",
    moCode: "22MO0084",
    mgCode: "24MG0013",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 186,
    title: "Cloud Computing",
    moCode: "22MO0085",
    mgCode: "23MG0047",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 187,
    title: "Computational Complexity",
    moCode: "22MO0086",
    mgCode: "23MG0048",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 188,
    title: "Computational Number Theory and Algebra",
    moCode: "22MO0087",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 189,
    title: "Computer Graphics",
    moCode: "22MO0088",
    mgCode: "23MG0005",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 190,
    title: "Computer Vision",
    moCode: "22MO0089",
    mgCode: "23MG0049",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 191,
    title: "Cryptography And Network Security",
    moCode: "22MO0090",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 192,
    title: "Data Structure And Algorithms Using Java",
    moCode: "22MO0091",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 193,
    title: "Demystifying Networking",
    moCode: "22MO0092",
    mgCode: null,
    duration: "4",
    dept: "ECE",
  },
  {
    id: 194,
    title: "Design & Implementation of Human-Computer Interfaces",
    moCode: "22MO0093",
    mgCode: "23MG0050",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 195,
    title: "Design of Reinforced Concrete Structures",
    moCode: "22MO0094",
    mgCode: null,
    duration: "12",
    dept: "Civil",
  },
  {
    id: 196,
    title: "Distributed Systems",
    moCode: "22MO0095",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 197,
    title: "Embedded System Design with ARM",
    moCode: "22MO0096",
    mgCode: "23MG0051",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 198,
    title: "English Literature for competitive exams",
    moCode: "22MO0097",
    mgCode: null,
    duration: "8",
    dept: "Food",
  },
  {
    id: 199,
    title: "Foundation of Cloud IoT Edge ML",
    moCode: "22MO0098",
    mgCode: "23MG0052",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 200,
    title: "Foundations of Cyber Physical Systems",
    moCode: "22MO0099",
    mgCode: "24MG0014",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 201,
    title: "Foundations of R Software",
    moCode: "22MO0100",
    mgCode: "24MG0125",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 202,
    title: "Genetic Engineering: Theory and Application",
    moCode: "22MO0101",
    mgCode: "23MG0006",
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 203,
    title: "Geotechnical engineering laboratory",
    moCode: "22MO0102",
    mgCode: null,
    duration: "4",
    dept: "Civil",
  },
  {
    id: 204,
    title: "German - III",
    moCode: "22MO0103",
    mgCode: "24MG0015",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 205,
    title: "Hardware Modeling Using Verilog",
    moCode: "22MO0104",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 206,
    title: "Introduction to Airbreathing Propulsion",
    moCode: "22MO0105",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 207,
    title: "Introduction to Cell Biology",
    moCode: "22MO0106",
    mgCode: "24MG0016",
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 208,
    title:
      "Introduction to Computer and Network Performance Analysis using Queuing Systems",
    moCode: "22MO0107",
    mgCode: null,
    duration: "4",
    dept: "CSE",
  },
  {
    id: 209,
    title: "Introduction to Embedded System Design",
    moCode: "22MO0108",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 210,
    title: "Introduction To Fluid Mechanics",
    moCode: "22MO0109",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 211,
    title: "Introduction to Game Theory and Mechanism Design",
    moCode: "22MO0110",
    mgCode: "23MG0053",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 212,
    title: "Introduction To Haskell Programming",
    moCode: "22MO0111",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 213,
    title: "Introduction to Japanese Language and Culture - II",
    moCode: "22MO0112",
    mgCode: "24MG0092",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 214,
    title: "Introduction To Machine Learning",
    moCode: "22MO0113",
    mgCode: "24MG0108",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 215,
    title: "Introduction to Quantum Computing: Quantum Algorithms and Qiskit",
    moCode: "22MO0114",
    mgCode: "24MG0093",
    duration: "4",
    dept: "CSE",
  },
  {
    id: 216,
    title: "Introduction to Wireless and Cellular Communications",
    moCode: "22MO0115",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 217,
    title: "Lighter than Air Systems",
    moCode: "22MO0116",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 218,
    title: "Machine Learning for Earth System Sciences",
    moCode: "22MO0117",
    mgCode: "23MG0054",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 219,
    title: "Mechanics and Control of Robotic Manipulators",
    moCode: "22MO0118",
    mgCode: null,
    duration: "8",
    dept: "Mech",
  },
  {
    id: 220,
    title: "Medical Image Analysis",
    moCode: "22MO0119",
    mgCode: null,
    duration: "4",
    dept: "Biomedical",
  },
  {
    id: 221,
    title: "Natural Language Processing",
    moCode: "22MO0120",
    mgCode: "24MG0017",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 222,
    title: "Object Oriented Analysis And Design",
    moCode: "22MO0121",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 223,
    title: "Organ Printing",
    moCode: "22MO0122",
    mgCode: "24MG0120",
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 224,
    title: "Parameterized Algorithms",
    moCode: "22MO0123",
    mgCode: "23MG0055",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 225,
    title: "Plastic Waste Management",
    moCode: "22MO0124",
    mgCode: "24MG0018",
    duration: "8",
    dept: "Civil",
  },
  {
    id: 226,
    title:
      "Post Harvest Operations and Processing of Fruits, Vegetables, Spices and Plantation Crop Products",
    moCode: "22MO0125",
    mgCode: "24MG0118",
    duration: "12",
    dept: "Food",
  },
  {
    id: 227,
    title: "Privacy and Security in Online Social Media",
    moCode: "22MO0126",
    mgCode: "23MG0056",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 228,
    title: "Product Design and Development",
    moCode: "22MO0127",
    mgCode: null,
    duration: "4",
    dept: "Mech",
  },
  {
    id: 229,
    title: "Product Engineering and Design Thinking",
    moCode: "22MO0128",
    mgCode: "23MG0003",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 230,
    title: "Quantum Algorithms and Cryptography",
    moCode: "22MO0129",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 231,
    title: "Randomized Methods in Complexity",
    moCode: "22MO0130",
    mgCode: "24MG0094",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 232,
    title: "Rapid Manufacturing",
    moCode: "22MO0131",
    mgCode: "23MG0084",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 233,
    title: "Real-Time Systems",
    moCode: "22MO0132",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 234,
    title: "Rocket Propulsion",
    moCode: "22MO0133",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 235,
    title: "Satellite Attitude Dynamics and Control",
    moCode: "22MO0134",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 236,
    title: "Scalable Data Science",
    moCode: "22MO0135",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 237,
    title: "Secure Computation: Part I",
    moCode: "22MO0136",
    mgCode: "24MG0019",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 238,
    title: "Secure Computation: Part II",
    moCode: "22MO0137",
    mgCode: "23MG0057",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 239,
    title: "Selected Topics in Algorithms",
    moCode: "22MO0138",
    mgCode: "24MG0020",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 240,
    title: "Software Project Management",
    moCode: "22MO0139",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 241,
    title: "Spatial Informatics",
    moCode: "22MO0140",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 242,
    title: "Statistical learning for Reliability Analysis",
    moCode: "22MO0141",
    mgCode: "23MG0058",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 243,
    title: "Understanding Design",
    moCode: "22MO0142",
    mgCode: null,
    duration: "4",
    dept: "Aero",
  },
  {
    id: 244,
    title: "User-centric Computing for Human-Computer Interaction",
    moCode: "22MO0143",
    mgCode: "23MG0059",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 245,
    title: "Automatic Control",
    moCode: "22MO0144",
    mgCode: "24MG0021",
    duration: "8",
    dept: "Robo",
  },
  {
    id: 246,
    title: "System Design Through Verilog",
    moCode: "22MO0145",
    mgCode: "24MG0109",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 247,
    title: "Solar Energy Engineering and Technology",
    moCode: "22MO0146",
    mgCode: null,
    duration: "12",
    dept: "ROBO",
  },
  {
    id: 248,
    title: "Advances in Strategic Human Resource Management (HRM)",
    moCode: "22MO0147",
    mgCode: null,
    duration: "4",
    dept: "MBA",
  },
  {
    id: 249,
    title: "Business Statistics",
    moCode: "22MO0148",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 250,
    title: "Digital Marketing",
    moCode: "22MO0149",
    mgCode: null,
    duration: "15",
    dept: "MBA",
  },
  {
    id: 251,
    title: "E-Commerce",
    moCode: "22MO0150",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 252,
    title: "Effective Business Communication",
    moCode: "22MO0151",
    mgCode: null,
    duration: "6",
    dept: "MBA",
  },
  {
    id: 253,
    title: "Human Resource Management",
    moCode: "22MO0152",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 254,
    title: "International Marketing",
    moCode: "22MO0153",
    mgCode: "23MG0086",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 255,
    title: "Introduction to Banking and Financial Markets",
    moCode: "22MO0154",
    mgCode: null,
    duration: "4",
    dept: "MBA",
  },
  {
    id: 256,
    title: "Investment management",
    moCode: "22MO0155",
    mgCode: "23MG0087",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 257,
    title: "Marketing Management - II",
    moCode: "22MO0156",
    mgCode: "23MG0088",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 258,
    title: "MS 2: Management of Human Resources",
    moCode: "22MO0157",
    mgCode: null,
    duration: "16",
    dept: "MBA",
  },
  {
    id: 259,
    title: "Quality Control and Improvement with MINITAB",
    moCode: "22MO0158",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 260,
    title: "Sales and Distribution Management",
    moCode: "22MO0159",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 261,
    title: "Supply Chain Analytics",
    moCode: "22MO0160",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 262,
    title: "Plant Developmental Biology",
    moCode: "22MO0161",
    mgCode: "24MG0060",
    duration: "4",
    dept: "Biotech",
  },
  {
    id: 263,
    title: "Computational Science in Engineering",
    moCode: "22MO0162",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 264,
    title: "Laws of Thermodynamics",
    moCode: "22MO0163",
    mgCode: null,
    duration: "4",
    dept: "Aero",
  },
  {
    id: 265,
    title: "Elastic Stability of Structures",
    moCode: "22MO0164",
    mgCode: null,
    duration: "12",
    dept: "Civil",
  },
  {
    id: 266,
    title:
      "Cooling Technology: Why and How utilized in Food Processing and allied Industries",
    moCode: "22MO0165",
    mgCode: "24MG0022",
    duration: "12",
    dept: "Food",
  },
  {
    id: 267,
    title: "The Psychology Of Language",
    moCode: "22MO0166",
    mgCode: "23MG0016",
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 268,
    title: "Introduction to Advanced Cognitive Processes",
    moCode: "22MO0167",
    mgCode: "23MG0017",
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 269,
    title: "An Introduction to Indian Literary Theory",
    moCode: "22MO0168",
    mgCode: null,
    duration: "8",
    dept: "CRIMINOLOGY",
  },
  {
    id: 270,
    title: "Proficiency Course in French",
    moCode: "22MO0172",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 271,
    title: "Real Time Operating System",
    moCode: "22MO0173",
    mgCode: null,
    duration: "4",
    dept: "ECE",
  },
  {
    id: 272,
    title: "Advanced Robotics",
    moCode: "23MO0001",
    mgCode: null,
    duration: "12",
    dept: "Robo",
  },
  {
    id: 273,
    title: "Air Pollution and Control",
    moCode: "23MO0002",
    mgCode: "24MG0023",
    duration: "12",
    dept: "Civil",
  },
  {
    id: 274,
    title: "Android Mobile Application Development",
    moCode: "23MO0003",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 275,
    title: "Basic Electronics",
    moCode: "23MO0004",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 276,
    title: "Basics of Mental Health & Clinical Psychiatry",
    moCode: "23MO0005",
    mgCode: null,
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 277,
    title: "Biological process design for wastewater treatment",
    moCode: "23MO0006",
    mgCode: "23MG0093",
    duration: "8",
    dept: "Civil",
  },
  {
    id: 278,
    title: "Brand Management",
    moCode: "23MO0007",
    mgCode: "24MG0024",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 279,
    title: "Business Analytics & Text Mining Modeling Using Python",
    moCode: "23MO0008",
    mgCode: null,
    duration: "8",
    dept: "Biomedical",
  },
  {
    id: 280,
    title: "Business To Business Marketing (B2B)",
    moCode: "23MO0009",
    mgCode: "24MG0025",
    duration: "12",
    dept: "DSCS",
  },
  {
    id: 281,
    title: "Communication Networks",
    moCode: "23MO0011",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 282,
    title: "Data Base Management System",
    moCode: "23MO0012",
    mgCode: "24MG0026",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 283,
    title: "Data Science for Engineers",
    moCode: "23MO0013",
    mgCode: "23MG0060",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 284,
    title: "Development and Applications of Special Concretes",
    moCode: "23MO0014",
    mgCode: null,
    duration: "8",
    dept: "Civil",
  },
  {
    id: 285,
    title: "Drug Delivery: Principles and Engineering",
    moCode: "23MO0015",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 286,
    title: "Electronic Systems For Cancer Diagnosis",
    moCode: "23MO0016",
    mgCode: "24MG0078",
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 287,
    title: "Electronic Waste Management - Issues And Challenges",
    moCode: "23MO0017",
    mgCode: null,
    duration: "4",
    dept: "Food",
  },
  {
    id: 288,
    title: "Engineering Statistics",
    moCode: "23MO0018",
    mgCode: "23MG0004",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 289,
    title: "Entrepreneurship",
    moCode: "23MO0019",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 290,
    title: "Financial Accounting",
    moCode: "23MO0020",
    mgCode: "23MG0018",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 291,
    title: "Fuzzy Logic And Neural Networks",
    moCode: "23MO0021",
    mgCode: null,
    duration: "8",
    dept: "ECE",
  },
  {
    id: 292,
    title: "Graph Theory",
    moCode: "23MO0022",
    mgCode: null,
    duration: "8",
    dept: "CSE",
  },
  {
    id: 293,
    title: "Indian Knowledge System(IKS): Humanities and Social Sciences",
    moCode: "23MO0023",
    mgCode: null,
    duration: "10",
    dept: "MBA",
  },
  {
    id: 294,
    title: "Innovation by Design",
    moCode: "23MO0024",
    mgCode: null,
    duration: "4",
    dept: "Mech",
  },
  {
    id: 295,
    title: "Introduction to Machine Learning",
    moCode: "23MO0025",
    mgCode: "23MG0069",
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 296,
    title: "Introduction To Mechanical Micro Machining",
    moCode: "23MO0026",
    mgCode: null,
    duration: "12",
    dept: "Mechanical",
  },
  {
    id: 297,
    title: "Machine Learning,ML",
    moCode: "23MO0027",
    mgCode: null,
    duration: "8",
    dept: "ECE",
  },
  {
    id: 298,
    title: "Marketing Management - I",
    moCode: "23MO0028",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 299,
    title: "Maternal Infant Young Child Nutrition",
    moCode: "23MO0029",
    mgCode: "24MG0027",
    duration: "12",
    dept: "Food",
  },
  {
    id: 300,
    title: "Mechatronics",
    moCode: "23MO0030",
    mgCode: "24MG0066",
    duration: "8",
    dept: "Robo",
  },
  {
    id: 301,
    title: "Metabolic Engineering",
    moCode: "23MO0031",
    mgCode: null,
    duration: "8",
    dept: "Food",
  },
  {
    id: 302,
    title: "Natural Hazards",
    moCode: "23MO0032",
    mgCode: "24MG0028",
    duration: "8",
    dept: "Civil",
  },
  {
    id: 303,
    title: "Operations And Supply Chain Management",
    moCode: "23MO0033",
    mgCode: null,
    duration: "12",
    dept: "MBA",
  },
  {
    id: 304,
    title: "Principles of Management",
    moCode: "23MO0034",
    mgCode: null,
    duration: "12",
    dept: "Commerce",
  },
  {
    id: 305,
    title: "Product and Brand Management",
    moCode: "23MO0035",
    mgCode: null,
    duration: "12",
    dept: "Biomedical",
  },
  {
    id: 306,
    title: "Project Management",
    moCode: "23MO0036",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 307,
    title: "Project Management : Planning, Execution, Evaluation And Control",
    moCode: "23MO0037",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 308,
    title: "Signal Processing Techniques and its Applications",
    moCode: "23MO0038",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 309,
    title: "Soil and Water Conservation Engineering",
    moCode: "23MO0039",
    mgCode: null,
    duration: "12",
    dept: "Food",
  },
  {
    id: 310,
    title: "Strategies for Sustainable Design",
    moCode: "23MO0040",
    mgCode: null,
    duration: "12",
    dept: "Civil",
  },
  {
    id: 311,
    title: "Towards an Ethical Digital Society: From Theory to Practice",
    moCode: "23MO0041",
    mgCode: null,
    duration: "4",
    dept: "Biomedical",
  },
  {
    id: 312,
    title: "Toyota Production System",
    moCode: "23MO0042",
    mgCode: "23MG0089",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 313,
    title: "Urban Services Planning",
    moCode: "23MO0043",
    mgCode: null,
    duration: "12",
    dept: "Civil",
  },
  {
    id: 314,
    title: "Wheeled Mobile Robots",
    moCode: "23MO0044",
    mgCode: "24MG0067",
    duration: "8",
    dept: "Robo",
  },
  {
    id: 315,
    title: "Municipal Solid Waste Management",
    moCode: "23MO0045",
    mgCode: "24MG0086",
    duration: "12",
    dept: "Mech",
  },
  {
    id: 316,
    title: "Aspen Plus simulation software - a basic course for beginners",
    moCode: "23MO0046",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 317,
    title: "Energy Conversion Technologies (Biomass And Coal)",
    moCode: "23MO0047",
    mgCode: null,
    duration: "8",
    dept: "Mech",
  },
  {
    id: 318,
    title:
      "Next Generation Sequencing Technologies : Data Analysis And Applications",
    moCode: "23MO0048",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 319,
    title: "Introduction To Proteogenomics",
    moCode: "23MO0049",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 320,
    title: "Cellular Biophysics: A Framework For Quantitative Biology",
    moCode: "23MO0050",
    mgCode: null,
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 321,
    title: "Medical Image Analysis",
    moCode: "23MO0051",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 322,
    title: "Principles Of Downstream Techniques In Bioprocess",
    moCode: "23MO0052",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 323,
    title: "Transport Phenomena In Biological Systems",
    moCode: "23MO0053",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 324,
    title: "Introduction To Biomedical Imaging Systems",
    moCode: "23MO0054",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 325,
    title: "Genome Editing And Engineering",
    moCode: "23MO0055",
    mgCode: "24MG0061",
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 326,
    title: "Introduction To Dynamical Models In Biology",
    moCode: "23MO0056",
    mgCode: null,
    duration: "4",
    dept: "Biotech",
  },
  {
    id: 327,
    title: "Functional Genomics",
    moCode: "23MO0057",
    mgCode: null,
    duration: "4",
    dept: "Biotech",
  },
  {
    id: 328,
    title: "Experimental Biotechnology",
    moCode: "23MO0058",
    mgCode: "23MG0010",
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 329,
    title: "Introduction To Mechanobiology",
    moCode: "23MO0059",
    mgCode: "24MG0113",
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 330,
    title: "Introduction To Proteomics",
    moCode: "23MO0060",
    mgCode: null,
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 331,
    title: "Computational Neuroscience",
    moCode: "23MO0061",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 332,
    title: "Neurobiology",
    moCode: "23MO0062",
    mgCode: null,
    duration: "4",
    dept: "Biotech",
  },
  {
    id: 333,
    title: "RNA Biology",
    moCode: "23MO0063",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 334,
    title: "Host-Pathogen Interaction (Immunology)",
    moCode: "23MO0064",
    mgCode: "23MG0012",
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 335,
    title: "Psychology Of Learning",
    moCode: "23MO0065",
    mgCode: "23MG0081",
    duration: "12",
    dept: "Criminology",
  },
  {
    id: 336,
    title: "Yoga And Positive Psychology For Managing Career And Life",
    moCode: "23MO0066",
    mgCode: "23MG0019",
    duration: "8",
    dept: "Criminology",
  },
  {
    id: 337,
    title: "Advance Course In Social Psychology",
    moCode: "23MO0067",
    mgCode: "23MG0082",
    duration: "12",
    dept: "Criminology",
  },
  {
    id: 338,
    title: "Design, Technology and Innovation",
    moCode: "23MO0068",
    mgCode: "23MG0001",
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 339,
    title: "Countering Stage Fright",
    moCode: "23MO0069",
    mgCode: null,
    duration: "4",
    dept: "Robotics",
  },
  {
    id: 340,
    title: "Robotics",
    moCode: "23MO0070",
    mgCode: "24MG0068",
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 341,
    title: "Food Packaging Technology",
    moCode: "23MO0071",
    mgCode: "23MG0075",
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 342,
    title: "Gender and literature",
    moCode: "23MO0072",
    mgCode: null,
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 343,
    title: "Foundations of Cognitive Robotics",
    moCode: "23MO0073",
    mgCode: null,
    duration: "4",
    dept: "Robotics",
  },
  {
    id: 344,
    title: "Product Design and Manufacturing",
    moCode: "23MO0074",
    mgCode: "24MG0056",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 345,
    title: "Entrepreneurship and IP strategy",
    moCode: "23MO0075",
    mgCode: null,
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 346,
    title: "Cyber Security and Privacy",
    moCode: "23MO0076",
    mgCode: "23MG0020",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 347,
    title: "Sensor Technologies: Physics, Fabrication, and Circuits",
    moCode: "23MO0077",
    mgCode: "24MG0110",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 348,
    title: "Operating System Fundamentals",
    moCode: "23MO0078",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 349,
    title: "Introduction to Operating Systems",
    moCode: "23MO0079",
    mgCode: "24MG0079",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 350,
    title: "Advance power electronics and Control",
    moCode: "23MO0080",
    mgCode: "24MG0126",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 351,
    title: "Advances In UHV Transmission And Distribution",
    moCode: "23MO0081",
    mgCode: null,
    duration: "8",
    dept: "ECE",
  },
  {
    id: 352,
    title: "Analog Communication",
    moCode: "23MO0082",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 353,
    title: "Customer Relationship Management",
    moCode: "23MO0083",
    mgCode: "23MG0090",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 354,
    title: "Modern Indian Architecture",
    moCode: "23MO0084",
    mgCode: "23MG0021",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 355,
    title: "Ecology And Environment",
    moCode: "23MO0085",
    mgCode: "23MG0022",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 356,
    title: "The Science of Happiness and Wellbeing",
    moCode: "23MO0086",
    mgCode: "23MG0023",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 357,
    title: "Body Language: Key To Professional Success",
    moCode: "23MO0087",
    mgCode: "23MG0024",
    duration: "4",
    dept: "Chemistry",
  },
  {
    id: 358,
    title: "Psychology Of Everyday",
    moCode: "23MO0088",
    mgCode: "23MG0025",
    duration: "4",
    dept: "Chemistry",
  },
  {
    id: 359,
    title: "Forensic Linguistics",
    moCode: "23MO0089",
    mgCode: "24MG0029",
    duration: "4",
    dept: "Chemistry",
  },
  {
    id: 360,
    title: "Cell Biology: Cellular organization, division and processes",
    moCode: "23MO0090",
    mgCode: "23MG0092",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 361,
    title: "Soft Skill Development",
    moCode: "23MO0091",
    mgCode: "23MG0026",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 362,
    title: "Enhancing Soft Skills and Personality",
    moCode: "23MO0092",
    mgCode: "24MG0030",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 363,
    title: "Oral Biology",
    moCode: "23MO0093",
    mgCode: null,
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 364,
    title: "Introduction to programming in C",
    moCode: "23MO0094",
    mgCode: "24MG0031",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 365,
    title: "Research Methodology",
    moCode: "23MO0095",
    mgCode: "24MG0124",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 366,
    title: "Constitutional Government & Democracy in India",
    moCode: "23MO0096",
    mgCode: null,
    duration: "15",
    dept: "Chemistry",
  },
  {
    id: 367,
    title: "Sports and Performance Nutrition",
    moCode: "23MO0097",
    mgCode: "24MG0032",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 368,
    title: "Human Movement Science",
    moCode: "23MO0098",
    mgCode: "24MG0084",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 369,
    title: "Intellectual Property",
    moCode: "23MO0099",
    mgCode: null,
    duration: "12",
    dept: "Chemistry",
  },
  {
    id: 370,
    title: "Entrepreneurship Essentials",
    moCode: "23MO0100",
    mgCode: null,
    duration: "12",
    dept: "Chemistry",
  },
  {
    id: 371,
    title: "Psychiatry - An Overview and How the Brain Creates Mind",
    moCode: "23MO0101",
    mgCode: "24MG0033",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 372,
    title: "Centre-State Relations in India",
    moCode: "23MO0102",
    mgCode: null,
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 373,
    title: "Consumer Psychology",
    moCode: "23MO0103",
    mgCode: "23MG0027",
    duration: "8",
    dept: "Chemistry",
  },
  {
    id: 374,
    title: "Business Law for Managers",
    moCode: "23MO0104",
    mgCode: null,
    duration: "8",
    dept: "MBA",
  },
  {
    id: 375,
    title: "Strategic Management \u2013 The Competitive Edge",
    moCode: "23MO0105",
    mgCode: "23MG0028",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 376,
    title: "Consumer Behaviour",
    moCode: "23MO0106",
    mgCode: "23MG0029",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 377,
    title: "Google Cloud Computing Foundations",
    moCode: "23MO0107",
    mgCode: "23MG0061",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 378,
    title: "Modern Algebra",
    moCode: "23MO0108",
    mgCode: "23MG0062",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 379,
    title: "Multi-Core Computer Architecture",
    moCode: "23MO0109",
    mgCode: "23MG0063",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 380,
    title: "Design And Analysis Of Algorithms",
    moCode: "23MO0110",
    mgCode: "23MG0064",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 381,
    title: "Software Testing",
    moCode: "23MO0111",
    mgCode: "23MG0065",
    duration: "4",
    dept: "CSE",
  },
  {
    id: 382,
    title: "Edge Computing",
    moCode: "23MO0112",
    mgCode: "23MG0066",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 383,
    title: "Linear programming and its applications to computer science",
    moCode: "23MO0113",
    mgCode: "23MG0067",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 384,
    title: "Basic Environmental Engineering And Pollution Abatement",
    moCode: "23MO0114",
    mgCode: "24MG0127",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 385,
    title: "Smart Structures",
    moCode: "23MO0115",
    mgCode: "23MG0070",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 386,
    title: "Corporate Social Responsibility",
    moCode: "23MO0116",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 387,
    title: "Design Of Fixed Wing Unmanned Aerial Vehicles",
    moCode: "23MO0117",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 388,
    title: "Environment And Development",
    moCode: "23MO0118",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 389,
    title: "Fundamentals Of Additive Manufacturing Technologies",
    moCode: "23MO0119",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 390,
    title: "Fundamentals Of Manufacturing Processes",
    moCode: "23MO0120",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 391,
    title: "Global Navigation Satellite Systems And Applications",
    moCode: "23MO0121",
    mgCode: null,
    duration: "4",
    dept: "Aero",
  },
  {
    id: 392,
    title: "Introduction To Composites",
    moCode: "23MO0122",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 393,
    title: "Introduction To Marketing Essentials",
    moCode: "23MO0123",
    mgCode: "23MG0071",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 394,
    title: "Knowledge Management",
    moCode: "23MO0124",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 395,
    title: "Mechanical Behavior Of Polymers And Composites",
    moCode: "23MO0125",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 396,
    title: "Metal Additive Manufacturing",
    moCode: "23MO0126",
    mgCode: "24MG0117",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 397,
    title: "Natural Resources Management",
    moCode: "23MO0127",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 398,
    title: "Organic Farming For Sustainable Agricultural Production",
    moCode: "23MO0128",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 399,
    title: "Postmodernism In Literature",
    moCode: "23MO0129",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 400,
    title: "Public Speaking",
    moCode: "23MO0130",
    mgCode: "23MG0072",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 401,
    title: "Sustainable Engineering Concepts And Life Cycle Analysis",
    moCode: "23MO0131",
    mgCode: "24MG0123",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 402,
    title: "Vibration And Structural Dynamics",
    moCode: "23MO0132",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 403,
    title: "Social Innovation In Industry 4.0",
    moCode: "23MO0133",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 404,
    title: "Industrial Robotics : Theories For Implementation",
    moCode: "23MO0134",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 405,
    title: "Laser Based Manufacturing",
    moCode: "23MO0135",
    mgCode: "24MG0129",
    duration: "8",
    dept: "Mech",
  },
  {
    id: 406,
    title:
      "Thermal Operations in Food Process Engineering: Theory and Applications",
    moCode: "23MO0136",
    mgCode: null,
    duration: "12",
    dept: "Food",
  },
  {
    id: 407,
    title: "Canning Technology, Value Addition Of Seafood (Fish Processing)",
    moCode: "23MO0137",
    mgCode: "23MG0076",
    duration: "8",
    dept: "Food",
  },
  {
    id: 408,
    title: "Advanced Aquaculture Technology",
    moCode: "23MO0138",
    mgCode: "23MG0077",
    duration: "12",
    dept: "Food",
  },
  {
    id: 409,
    title: "Building Materials And Composites",
    moCode: "23MO0139",
    mgCode: null,
    duration: "8",
    dept: "Civil",
  },
  {
    id: 410,
    title: "Integrated Waste Management For A Smart City",
    moCode: "23MO0140",
    mgCode: null,
    duration: "12",
    dept: "Civil",
  },
  {
    id: 411,
    title: "Project Planning & Control",
    moCode: "23MO0141",
    mgCode: null,
    duration: "8",
    dept: "Civil",
  },
  {
    id: 412,
    title: "Computational Genomics",
    moCode: "23MO0142",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 413,
    title: "Human Physiology",
    moCode: "23MO0143",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 414,
    title: "Pharmacognosy & Metabolic Engineering",
    moCode: "23MO0144",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 415,
    title: "Data Analysis For Biologists",
    moCode: "23MO0145",
    mgCode: "24MG0062",
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 416,
    title: "Interactomics : Basics & Applications",
    moCode: "23MO0146",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 417,
    title:
      "Thermodynamics for Biological Systems : Classical and Statistical Aspects",
    moCode: "23MO0147",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 418,
    title:
      "Optical Spectroscopy and Microscopy : Fundamentals of optical measurements and instrumentation",
    moCode: "23MO0148",
    mgCode: null,
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 419,
    title: "Biostatistics and Design of experiments",
    moCode: "23MO0149",
    mgCode: null,
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 420,
    title: "Foundation of R Software",
    moCode: "23MO0150",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 421,
    title: "Machine Learning And Deep Learning - Fundamentals And Applications",
    moCode: "23MO0151",
    mgCode: "23MG0080",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 422,
    title:
      "Applied Linear Algebra For Signal Processing, Data Analytics And Machine Learning",
    moCode: "23MO0152",
    mgCode: null,
    duration: "12",
    dept: "BME",
  },
  {
    id: 423,
    title: "E-Business",
    moCode: "23MO0153",
    mgCode: null,
    duration: "12",
    dept: "BME",
  },
  {
    id: 424,
    title: "Neural Science for Engineers",
    moCode: "23MO0154",
    mgCode: null,
    duration: "12",
    dept: "BME",
  },
  {
    id: 425,
    title: "Scientific Computing Using Python",
    moCode: "23MO0155",
    mgCode: "23MG0083",
    duration: "12",
    dept: "BME",
  },
  {
    id: 426,
    title: "I Think Biology",
    moCode: "23MO0156",
    mgCode: null,
    duration: "12",
    dept: "BME",
  },
  {
    id: 427,
    title: "Biomechanics of Joints and Orthopaedic Implants",
    moCode: "23MO0157",
    mgCode: null,
    duration: "8",
    dept: "BME",
  },
  {
    id: 428,
    title: "Non-conventional energy Resources",
    moCode: "23MO0158",
    mgCode: null,
    duration: "12",
    dept: "BME",
  },
  {
    id: 429,
    title: "Medical Law",
    moCode: "23MO0159",
    mgCode: null,
    duration: "8",
    dept: "BME",
  },
  {
    id: 430,
    title: "Roadmap for patent creation",
    moCode: "23MO0160",
    mgCode: null,
    duration: "8",
    dept: "BME",
  },
  {
    id: 431,
    title: "Business Analytics For Management Decision",
    moCode: "23MO0161",
    mgCode: null,
    duration: "12",
    dept: "Commerce",
  },
  {
    id: 432,
    title: "Introduction to Ancient Indian Technology",
    moCode: "23MO0162",
    mgCode: null,
    duration: "8",
    dept: "Physical Sciences",
  },
  {
    id: 433,
    title: "Understanding Ethnography",
    moCode: "23MO0163",
    mgCode: null,
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 434,
    title: "Basic Linear Algebra",
    moCode: "23MO0164",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 435,
    title: "Waste to Energy Conversion",
    moCode: "23MO0165",
    mgCode: "24MG0131",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 436,
    title: "Effective Writing",
    moCode: "23MO0166",
    mgCode: null,
    duration: "4",
    dept: "Mechanical",
  },
  {
    id: 437,
    title: "Inspection and Quality Control in Manufacturing",
    moCode: "23MO0167",
    mgCode: null,
    duration: "4",
    dept: "Mechanical",
  },
  {
    id: 438,
    title: "Surface Engineering of Nanomaterials",
    moCode: "23MO0168",
    mgCode: null,
    duration: "8",
    dept: "Mechanical",
  },
  {
    id: 439,
    title: "Manufacturing Guidelines for Product Design",
    moCode: "23MO0169",
    mgCode: null,
    duration: "8",
    dept: "Mechanical",
  },
  {
    id: 440,
    title: "Integrated Marketing Management",
    moCode: "23MO0171",
    mgCode: "23MG0094",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 441,
    title: "Retail Management",
    moCode: "23MO0172",
    mgCode: "23MG0095",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 442,
    title: "Strategic Performance Management",
    moCode: "23MO0173",
    mgCode: "23MG0096",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 443,
    title: "Business Forecasting",
    moCode: "23MO0174",
    mgCode: "23MG0097",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 444,
    title: "Behavioral And Personal Finance",
    moCode: "23MO0175",
    mgCode: "23MG0098",
    duration: "8",
    dept: "MBA",
  },
  {
    id: 445,
    title: "Principles of Industrial Engineering",
    moCode: "23MO0183",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 446,
    title: "Subsurface exploration :importance and techniques involved",
    moCode: "23MO0185",
    mgCode: null,
    duration: "8",
    dept: "Civil",
  },
  {
    id: 447,
    title: "Introduction to Civil Engineering Profession",
    moCode: "23MO0186",
    mgCode: "24MG0034",
    duration: "8",
    dept: "Civil",
  },
  {
    id: 448,
    title:
      "Aspen Plus\u00ae simulation software - a basic course for beginners",
    moCode: "23MO0188",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 449,
    title:
      "Modern Food Packaging Technologies: Regulatory Aspects and Global Trends",
    moCode: "23MO0189",
    mgCode: "24MG0035",
    duration: "12",
    dept: "Food",
  },
  {
    id: 450,
    title: "Industrial Hydraulics and Automation",
    moCode: "23MO0190",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 451,
    title: "Discrete Mathematics",
    moCode: "23MO0197",
    mgCode: null,
    duration: "12",
    dept: "CSE",
  },
  {
    id: 452,
    title:
      "Business Fundamentals for Entrepreneurs (Part 2: External Operation)",
    moCode: "23MO0204",
    mgCode: null,
    duration: "4",
    dept: "Aero",
  },
  {
    id: 453,
    title: "Patent Drafting for Beginners",
    moCode: "23MO0205",
    mgCode: null,
    duration: "4",
    dept: "Aero",
  },
  {
    id: 454,
    title: "UAV in Engineering Applications",
    moCode: "23MO0206",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 455,
    title: "Sociology and Sanitation: An Introduction",
    moCode: "24MO0001",
    mgCode: "24MG0036",
    duration: "4",
    dept: "Aero",
  },
  {
    id: 456,
    title: "Combustion of Solid Fuels and Propellants",
    moCode: "24MO0002",
    mgCode: "24MG0037",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 457,
    title: "Computer Integrated Manufacturing",
    moCode: "24MO0003",
    mgCode: "24MG0038",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 458,
    title: "Cryogenic Hydrogen Technology",
    moCode: "24MO0004",
    mgCode: "24MG0039",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 459,
    title: "Economic Growth and Development",
    moCode: "24MO0005",
    mgCode: "24MG0040",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 460,
    title: "Energy Resources, Economics, and Sustainability",
    moCode: "24MO0006",
    mgCode: "24MG0041",
    duration: "8",
    dept: "Aero",
  },
  {
    id: 461,
    title: "Psychology of Stress, Health and Well-being",
    moCode: "24MO0007",
    mgCode: "24MG0042",
    duration: "12",
    dept: "Aero",
  },
  {
    id: 462,
    title: "Basics of Health Promotion and Education Intervention",
    moCode: "24MO0008",
    mgCode: "24MG0043",
    duration: "8",
    dept: "BME",
  },
  {
    id: 463,
    title: "Introduction to Cognitive Psychology",
    moCode: "24MO0009",
    mgCode: "24MG0044",
    duration: "12",
    dept: "BME",
  },
  {
    id: 464,
    title:
      "Biomedical Ultrasound: Fundamentals of Imaging and Micromachined Transducers",
    moCode: "24MO0010",
    mgCode: "24MG0045",
    duration: "12",
    dept: "BME",
  },
  {
    id: 465,
    title: "Basics of Computational Complexity",
    moCode: "24MO0011",
    mgCode: "24MG0047",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 466,
    title: "Advanced Computer Architecture",
    moCode: "24MO0012",
    mgCode: "24MG0048",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 467,
    title: "Parallel Computer Architecture",
    moCode: "24MO0013",
    mgCode: "24MG0049",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 468,
    title: "Games and Information",
    moCode: "24MO0014",
    mgCode: "24MG0050",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 469,
    title: "Business Intelligence & Analytics",
    moCode: "24MO0015",
    mgCode: "24MG0051",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 470,
    title: "Probability for Computer Science",
    moCode: "24MO0016",
    mgCode: "24MG0052",
    duration: "8",
    dept: "CSE",
  },
  {
    id: 471,
    title: "Optical Wireless Communications for Beyond 5G Networks and IoT",
    moCode: "24MO0017",
    mgCode: null,
    duration: "12",
    dept: "ECE",
  },
  {
    id: 472,
    title: "Digital Design with Verilog",
    moCode: "24MO0018",
    mgCode: "24MG0053",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 473,
    title: "Computer Networks and Internet Protocol",
    moCode: "24MO0019",
    mgCode: "24MG0054",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 474,
    title:
      "Computer Vision and Image Processing - Fundamentals and Applications",
    moCode: "24MO0020",
    mgCode: "24MG0055",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 475,
    title: "Manufacturing Process Technology I & II",
    moCode: "24MO0021",
    mgCode: null,
    duration: "12",
    dept: "Mech",
  },
  {
    id: 476,
    title: "Principles Of Casting Technology",
    moCode: "24MO0022",
    mgCode: null,
    duration: "8",
    dept: "Mech",
  },
  {
    id: 477,
    title: "Introduction to Graph Algorithms",
    moCode: "24MO0023",
    mgCode: "24MG0063",
    duration: "8",
    dept: "DSCS",
  },
  {
    id: 478,
    title: "Artificial Intelligence for Economics",
    moCode: "24MO0024",
    mgCode: "24MG0064",
    duration: "8",
    dept: "DSCS",
  },
  {
    id: 479,
    title: "Deep Learning for Computer Vision",
    moCode: "24MO0025",
    mgCode: "24MG0065",
    duration: "12",
    dept: "DSCS",
  },
  {
    id: 480,
    title: "Sustainable Energy Technology",
    moCode: "24MO0026",
    mgCode: "24MG0122",
    duration: "12",
    dept: "MECH",
  },
  {
    id: 481,
    title: "Technical Communication for Engineers",
    moCode: "24MO0027",
    mgCode: null,
    duration: "4",
    dept: "MECH",
  },
  {
    id: 482,
    title: "Welding Application Technology",
    moCode: "0",
    mgCode: "24MG0070",
    duration: "8",
    dept: "MECH",
  },
  {
    id: 483,
    title: "Distributed Optimization and Machine Learning",
    moCode: "24MO0028",
    mgCode: "24MG0071",
    duration: "12",
    dept: "AIML",
  },
  {
    id: 484,
    title: "Responsible & Safe AI Systems",
    moCode: "24MO0029",
    mgCode: "24MG0073",
    duration: "12",
    dept: "AIML",
  },
  {
    id: 485,
    title:
      "Electronic Systems Design: Hands-on Circuits and PCB Design with CAD Software",
    moCode: "24MO0030",
    mgCode: "24MG0075",
    duration: "12",
    dept: "BME",
  },
  {
    id: 486,
    title: "Programming in Python",
    moCode: "24MO0031",
    mgCode: "24MG0076",
    duration: "12",
    dept: "BME",
  },
  {
    id: 487,
    title: "Immunology",
    moCode: "24MO0032",
    mgCode: "24MG0077",
    duration: "12",
    dept: "BME",
  },
  {
    id: 488,
    title: "Sustainable Happiness",
    moCode: "24MO0033",
    mgCode: "24MG0080",
    duration: "8",
    dept: "BME",
  },
  {
    id: 489,
    title: "Management of Medical Emergencies in Dental Practice",
    moCode: "24MO0034",
    mgCode: "24MG0082",
    duration: "8",
    dept: "BME",
  },
  {
    id: 490,
    title: "Modern Construction Materials",
    moCode: "24MO0035",
    mgCode: "24MG0085",
    duration: "12",
    dept: "Civil",
  },
  {
    id: 491,
    title: "Business Development: From Start to Scale",
    moCode: "24MO0036",
    mgCode: "24MG0087",
    duration: "12",
    dept: "Commerce",
  },
  {
    id: 492,
    title: "AI in Marketing",
    moCode: "24MO0037",
    mgCode: "24MG0088",
    duration: "12",
    dept: "Commerce",
  },
  {
    id: 493,
    title: "Fundamentals of Cost Accounting",
    moCode: "24MO0038",
    mgCode: "24MG0089",
    duration: "8",
    dept: "Commerce",
  },
  {
    id: 494,
    title: "Practical Cyber Security for Cyber Security Practitioners",
    moCode: "24MO0039",
    mgCode: "24MG0095",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 495,
    title: "Computational Arithmetic - Geometry for Algebraic Curves",
    moCode: "24MO0040",
    mgCode: "24MG0096",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 496,
    title: "Social Network Analysis",
    moCode: "24MO0041",
    mgCode: "24MG0097",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 497,
    title: "Approximation Algorithm",
    moCode: "24MO0042",
    mgCode: "24MG0098",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 498,
    title: "VLSI Design Flow: RTL to GDS",
    moCode: "24MO0043",
    mgCode: "24MG0099",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 499,
    title: "Principles of Modern CDMA/ MIMO/ OFDM Wireless Communications",
    moCode: "24MO0044",
    mgCode: "24MG0100",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 500,
    title: "Modern Digital Communication Techniques",
    moCode: "24MO0045",
    mgCode: "24MG0101",
    duration: "12",
    dept: "ECE",
  },
  {
    id: 501,
    title:
      "Artificial Intelligence and Machine Learning in Materials Engineering",
    moCode: "24MO0046",
    mgCode: "24MG0102",
    duration: "12",
    dept: "Mech",
  },
  {
    id: 502,
    title: "Nature and Properties of Materials-An Introductory Course",
    moCode: "24MO0047",
    mgCode: "24MG0103",
    duration: "8",
    dept: "Mech",
  },
  {
    id: 503,
    title: "Introduction to Language and Linguistics",
    moCode: "24MO0048",
    mgCode: "24MG0104",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 504,
    title: "Korean I",
    moCode: "24MO0049",
    mgCode: "24MG0105",
    duration: "12",
    dept: "CSE",
  },
  {
    id: 505,
    title: "Introduction to Biomimicry",
    moCode: "24MO0050",
    mgCode: "24MG0114",
    duration: "8",
    dept: "Biotech",
  },
  {
    id: 506,
    title: "Cognition and its Computation",
    moCode: "24MO0051",
    mgCode: "24MG0115",
    duration: "12",
    dept: "Biotech",
  },
  {
    id: 507,
    title: "An Introduction to Climate Dynamics, Variability and Monitoring",
    moCode: "24MO0052",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 508,
    title: "ANIMATIONs",
    moCode: "24MO0053",
    mgCode: null,
    duration: "15",
    dept: "Aero",
  },
  {
    id: 509,
    title: "Conservation Geography",
    moCode: "24MO0054",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 510,
    title: "Educational Leadership",
    moCode: "24MO0055",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 511,
    title: "Ethics in Engineering Practice",
    moCode: "24MO0056",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 512,
    title: "Hydrogen Energy: Production, Storage, Transportation and Safety",
    moCode: "24MO0057",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 513,
    title:
      "Introduction to Basic Spoken Sanskrit and Intermediate Level of Spoken Sanskrit",
    moCode: "24MO0058",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 514,
    title:
      "Introduction To Environmental Engineering And Science - Fundamental And Sustainability Concepts",
    moCode: "24MO0059",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 515,
    title: "Introduction to Exercise Physiology & Sports Performance",
    moCode: "24MO0060",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 516,
    title: "Introduction to Urban Planning",
    moCode: "24MO0061",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 517,
    title: "Materials Processing (Casting, Forming and Welding)",
    moCode: "24MO0062",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 518,
    title: "Metallurgical and Electronic Waste Recycling",
    moCode: "24MO0063",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 519,
    title: "Personality Development",
    moCode: "24MO0064",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 520,
    title: "Physics of Renewable Energy Systems",
    moCode: "24MO0065",
    mgCode: null,
    duration: "12",
    dept: "Aero",
  },
  {
    id: 521,
    title: "Principles of Metal Forming Technology",
    moCode: "24MO0066",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 522,
    title: "Remote Sensing and GIS",
    moCode: "24MO0067",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 523,
    title: "Research Ethics and Plagiarism",
    moCode: "24MO0068",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 524,
    title: "Understanding Disciplines and Subjects",
    moCode: "24MO0069",
    mgCode: null,
    duration: "8",
    dept: "Aero",
  },
  {
    id: 525,
    title: "Business and Sustainable Development",
    moCode: "24MO0070",
    mgCode: null,
    duration: "4",
    dept: "ECE",
  },
  {
    id: 526,
    title:
      "Business Fundamentals for Entrepreneurs (Part 1: Internal Operation)",
    moCode: "24MO0071",
    mgCode: null,
    duration: "4",
    dept: "ECE",
  },
  {
    id: 527,
    title: "CMOS Digital VLSI Design",
    moCode: "24MO0072",
    mgCode: "24MG0128",
    duration: "8",
    dept: "ECE",
  },
  {
    id: 528,
    title: "Indian Poetry in English",
    moCode: "24MO0073",
    mgCode: null,
    duration: "8",
    dept: "Robotics",
  },
  {
    id: 529,
    title: "Microbial Biotechnology",
    moCode: "0",
    mgCode: "24MG0130",
    duration: "12",
    dept: "0",
  },
];
